// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Проверяет nickname и password, кладёт JWT на 12 часов в HttpOnly cookie ` + "`" + `access_token` + "`" + `. Из Swagger UI cookie сохранится в браузере, дальше защищённые запросы уйдут с ней автоматически.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход",
                "parameters": [
                    {
                        "description": "Учётные данные",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Вошедший пользователь, cookie в заголовке Set-Cookie",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректное тело запроса",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверный nickname или пароль",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Удаляет cookie ` + "`" + `access_token` + "`" + `. Сам JWT остаётся валидным до истечения срока — серверного списка отзыва нет.",
                "tags": [
                    "auth"
                ],
                "summary": "Выход",
                "responses": {
                    "204": {
                        "description": "Cookie удалена"
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Возвращает профиль владельца cookie ` + "`" + `access_token` + "`" + `. Удобно для проверки, что вход прошёл.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Текущий пользователь",
                "responses": {
                    "200": {
                        "description": "Профиль текущего пользователя",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или истекла cookie access_token",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "Справочник для полей ` + "`" + `category` + "`" + ` и ` + "`" + `wants` + "`" + `. Слаг — стабильный ключ, название меняется, слаг нет.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Список категорий",
                "responses": {
                    "200": {
                        "description": "Категории",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_item_dto.CategoryResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    }
                }
            }
        },
        "/exchanges": {
            "get": {
                "description": "Возвращает все найденные обмены текущего пользователя вместе с участниками и объявлениями.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchanges"
                ],
                "summary": "Получить свои обмены",
                "responses": {
                    "200": {
                        "description": "Список обменов; если обменов нет, возвращается []",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ExchangeResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exchanges/{id}": {
            "get": {
                "description": "Доступен только участнику этого обмена.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchanges"
                ],
                "summary": "Получить обмен по ID",
                "parameters": [
                    {
                        "type": "string",
                        "example": "8db9f3e2-8a45-4a70-b3d1-167b4f97e121",
                        "description": "UUID обмена",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обмен",
                        "schema": {
                            "$ref": "#/definitions/dto.ExchangeResponse"
                        }
                    },
                    "400": {
                        "description": "ID не является UUID",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Пользователь не участвует в обмене",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Обмен не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exchanges/{id}/complete": {
            "post": {
                "description": "Сохраняет подтверждение текущего участника. После подтверждения всеми участниками обмен завершается, объявления помечаются переданными, а счётчики завершённых обменов увеличиваются.",
                "tags": [
                    "exchanges"
                ],
                "summary": "Подтвердить получение вещи",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID обмена",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Получение подтверждено"
                    },
                    "400": {
                        "description": "ID не является UUID",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Пользователь не участвует в обмене",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Обмен не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Обмен ещё не подтверждён или уже отменён",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exchanges/{id}/confirm": {
            "post": {
                "description": "Сохраняет согласие текущего участника. После согласия всех участников обмен подтверждается, а объявления резервируются.",
                "tags": [
                    "exchanges"
                ],
                "summary": "Подтвердить участие в обмене",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID обмена",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Участие подтверждено"
                    },
                    "400": {
                        "description": "ID не является UUID",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Пользователь не участвует в обмене",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Обмен не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Решение уже принято, обмен закрыт или объявление недоступно",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exchanges/{id}/decline": {
            "post": {
                "description": "Сохраняет отказ текущего участника и отменяет предложенный обмен.",
                "tags": [
                    "exchanges"
                ],
                "summary": "Отказаться от участия в обмене",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID обмена",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Отказ сохранён, обмен отменён"
                    },
                    "400": {
                        "description": "ID не является UUID",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Пользователь не участвует в обмене",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Обмен не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Решение уже принято или обмен закрыт",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exchanges/{id}/messages": {
            "get": {
                "description": "Возвращает обсуждение и события обмена одной лентой в хронологическом порядке. Доступен только участнику.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchanges"
                ],
                "summary": "Прочитать тред обмена",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID обмена",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Тред; если сообщений нет, возвращается []",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.MessageResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "ID не является UUID",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Пользователь не участвует в обмене",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Обмен не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Добавляет сообщение участника в обсуждение обмена. Писать могут только участники и только пока обмен не закрыт.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchanges"
                ],
                "summary": "Написать в тред обмена",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID обмена",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Текст сообщения",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Сообщение добавлено",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "ID не является UUID или текст пустой либо длиннее 2000 символов",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Пользователь не участвует в обмене",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Обмен не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Обмен закрыт: тред доступен только на чтение",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Отвечает 200, если процесс поднят. Состояние БД не проверяет.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Проверка живости сервиса",
                "responses": {
                    "200": {
                        "description": "сервис работает",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/items": {
            "get": {
                "description": "Требует cookie ` + "`" + `access_token` + "`" + `. Возвращает все объявления текущего пользователя\nлюбого статуса, от новых к старым. Чужие объявления этим маршрутом не отдаются.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Получить свои объявления",
                "responses": {
                    "200": {
                        "description": "Список объявлений; если их нет, возвращается []",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ItemResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Нет или истекла cookie access_token",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    }
                }
            },
            "post": {
                "description": "Требует cookie ` + "`" + `access_token` + "`" + `. Владелец берётся из токена, а не из тела запроса.\nНужна хотя бы одна фотография (ссылкой) и хотя бы одна желаемая категория —\nбез них объявление не участвует в подборе обменов. Список категорий: GET /categories.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Создать объявление",
                "parameters": [
                    {
                        "description": "Данные объявления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateItemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Создано, ссылка на объявление в заголовке Location",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректное тело запроса, нет фото или желаний, неизвестная категория",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "401": {
                        "description": "Нет или истекла cookie access_token",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    }
                }
            }
        },
        "/items/{id}": {
            "get": {
                "description": "Публичная карточка вещи: фотографии, желаемые категории и статус. Аутентификация не нужна.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Получить объявление по ID",
                "parameters": [
                    {
                        "type": "string",
                        "example": "8db9f3e2-8a45-4a70-b3d1-167b4f97e121",
                        "description": "UUID объявления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Объявление",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemResponse"
                        }
                    },
                    "400": {
                        "description": "ID не является UUID",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "404": {
                        "description": "Объявление не найдено",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Требует cookie ` + "`" + `access_token` + "`" + `, удалять можно только свои объявления. Вещь, уже занятую\nв незавершённом обмене, удалить нельзя: иначе участник остался бы без обещанного предмета.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Удалить своё объявление",
                "parameters": [
                    {
                        "type": "string",
                        "example": "8db9f3e2-8a45-4a70-b3d1-167b4f97e121",
                        "description": "UUID объявления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Удалено"
                    },
                    "400": {
                        "description": "ID не является UUID",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "401": {
                        "description": "Нет или истекла cookie access_token",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "403": {
                        "description": "Объявление принадлежит другому пользователю",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "404": {
                        "description": "Объявление не найдено",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "409": {
                        "description": "Вещь участвует в незавершённом обмене",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Требует cookie ` + "`" + `access_token` + "`" + `, менять можно только свои объявления. Достаточно одного поля.\n` + "`" + `photo_urls` + "`" + ` и ` + "`" + `wants` + "`" + ` заменяются целиком: чтобы добавить фотографию, пришлите старые\nссылки вместе с новой. Пустой список запрещён — у объявления всегда есть хотя бы одно фото.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Изменить своё объявление",
                "parameters": [
                    {
                        "type": "string",
                        "example": "8db9f3e2-8a45-4a70-b3d1-167b4f97e121",
                        "description": "UUID объявления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Поля, которые нужно изменить",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновлённое объявление",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректное тело, пустой список фото или желаний, неизвестная категория",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "401": {
                        "description": "Нет или истекла cookie access_token",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "403": {
                        "description": "Объявление принадлежит другому пользователю",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "404": {
                        "description": "Объявление не найдено",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "409": {
                        "description": "Нельзя изменить условия объявления в незавершённом обмене",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemError"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Регистрация: nickname 3–32 символа, пароль 8–72 байта. Пароль хранится bcrypt-хешем и в ответе не возвращается.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Создать пользователя",
                "parameters": [
                    {
                        "description": "Данные нового пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Создан, ссылка на профиль в заголовке Location",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректное тело запроса или нарушены ограничения полей",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Nickname уже занят",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/me/blocks": {
            "get": {
                "description": "Возвращает личный список блокировок текущего пользователя. Заблокированные пользователи об этом не уведомляются.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить список заблокированных пользователей",
                "responses": {
                    "200": {
                        "description": "Список блокировок; если он пуст, возвращается []",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.BlockedUserResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/me/blocks/{user_id}": {
            "post": {
                "description": "Исключает пользователя из будущих совместных обменов и отменяет общие неподтверждённые предложения. Повторный запрос безопасен.",
                "tags": [
                    "users"
                ],
                "summary": "Заблокировать пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID блокируемого пользователя",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Пользователь заблокирован"
                    },
                    "400": {
                        "description": "ID не является UUID или пользователь блокирует себя",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Блокируемый пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Разрешает попадание пользователя в новые совместные обмены. Существующие обмены не изменяются.",
                "tags": [
                    "users"
                ],
                "summary": "Разблокировать пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID разблокируемого пользователя",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Пользователь разблокирован"
                    },
                    "400": {
                        "description": "ID не является UUID или пользователь указывает себя",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Публичный профиль: рейтинг и счётчики сделок. Аутентификация не нужна.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить пользователя по ID",
                "parameters": [
                    {
                        "type": "string",
                        "example": "8db9f3e2-8a45-4a70-b3d1-167b4f97e121",
                        "description": "UUID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Профиль пользователя",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "ID не является UUID",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Требует cookie ` + "`" + `access_token` + "`" + ` (получить через POST /auth/login). Менять можно только собственный профиль. Достаточно одного поля, остальные останутся прежними.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Обновить свой профиль",
                "parameters": [
                    {
                        "type": "string",
                        "example": "8db9f3e2-8a45-4a70-b3d1-167b4f97e121",
                        "description": "UUID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Поля, которые нужно изменить",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновлённый профиль",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректное тело запроса, не передано ни одного поля или ID не UUID",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или истекла cookie access_token",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Попытка изменить чужой профиль",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Nickname уже занят",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BlockedUserResponse": {
            "type": "object",
            "properties": {
                "blocked_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                }
            }
        },
        "dto.CreateItemRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "bikes"
                },
                "description": {
                    "type": "string",
                    "example": "Почти новый, катался год"
                },
                "photo_urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://example.com/bike-1.jpg",
                        "https://example.com/bike-2.jpg"
                    ]
                },
                "title": {
                    "type": "string",
                    "example": "Велосипед"
                },
                "wants": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "consoles",
                        "phones"
                    ]
                }
            }
        },
        "dto.CreateMessageRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "Могу привезти в субботу к метро, удобно?"
                }
            }
        },
        "dto.CreateUserRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                }
            }
        },
        "dto.ExchangeResponse": {
            "type": "object",
            "properties": {
                "closed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ParticipantResponse"
                    }
                },
                "status": {
                    "type": "string"
                },
                "unread_count": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.ItemError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "dto.ItemResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "photo_urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "wants": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "properties": {
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.MessageResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/dto.ParticipantUserResponse"
                },
                "body": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                }
            }
        },
        "dto.ParticipantItemResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.CategoryResponse"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.ParticipantResponse": {
            "type": "object",
            "properties": {
                "completion_confirmed_at": {
                    "type": "string"
                },
                "decided_at": {
                    "type": "string"
                },
                "gives_item": {
                    "$ref": "#/definitions/dto.ParticipantItemResponse"
                },
                "position": {
                    "type": "integer"
                },
                "receives_item": {
                    "$ref": "#/definitions/dto.ParticipantItemResponse"
                },
                "status": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.ParticipantUserResponse"
                }
            }
        },
        "dto.ParticipantUserResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateItemRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "bikes"
                },
                "description": {
                    "type": "string",
                    "example": "Добавил фото рамы"
                },
                "photo_urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://example.com/bike-1.jpg",
                        "https://example.com/bike-3.jpg"
                    ]
                },
                "title": {
                    "type": "string",
                    "example": "Велосипед городской"
                },
                "wants": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "consoles"
                    ]
                }
            }
        },
        "dto.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deals_broken": {
                    "type": "integer"
                },
                "deals_completed": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.CategoryResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "github_com_sweetlife999_chain-of-trades-avito_internal_exchange_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "github_com_sweetlife999_chain-of-trades-avito_internal_item_dto.CategoryResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Велосипеды и транспорт"
                },
                "slug": {
                    "type": "string",
                    "example": "bikes"
                }
            }
        },
        "github_com_sweetlife999_chain-of-trades-avito_internal_user_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Цепочка обмена — API",
	Description:      "HTTP API сервиса многостороннего обмена вещами: профили пользователей, вход по JWT\nи объявления о вещах, которые владелец готов обменять.\n\nЗащищённые маршруты читают HttpOnly cookie `access_token`. Кнопки «Authorize» здесь нет\nи не нужно: выполните `POST /auth/login` прямо из этой страницы — браузер сохранит cookie\nи будет отправлять её со всеми следующими запросами сам.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
