import type { MascotEvent, MascotReaction } from "./mascot.types";

export const mascotReactions: Record<MascotEvent, MascotReaction> = {
  APP_OPENED: {
    mood: "hello",
    mode: "ambient",
    message: null,
    durationMs: 3200,
    anchor: null,
    movement: "roam",
  },
  AUTH_FORM_READY: {
    mood: "pointing",
    mode: "attention",
    message: "Заполните форму — кнопка продолжения здесь.",
    durationMs: null,
    anchor: "form-submit",
    movement: "approach",
  },
  FORM_SUBMIT: {
    mood: "thinking",
    mode: "attention",
    message: "Проверяю данные…",
    durationMs: null,
    anchor: "form-submit",
    movement: "approach",
  },
  FORM_SUCCESS: {
    mood: "celebrate",
    mode: "dialog",
    message: "Готово! Всё получилось.",
    durationMs: 4200,
    anchor: "form-submit",
    movement: "run",
  },
  FORM_ERROR: {
    mood: "sad",
    mode: "dialog",
    message: "Не получилось. Проверьте поля и попробуйте ещё раз.",
    durationMs: null,
    anchor: "form-submit",
    movement: "approach",
  },
  EMPTY_ITEMS: {
    mood: "bored",
    mode: "ambient",
    message: null,
    durationMs: null,
    anchor: "items-empty",
    movement: "wander",
  },
  EMPTY_EXCHANGES: {
    mood: "bored",
    mode: "ambient",
    message: null,
    durationMs: null,
    anchor: "exchanges-empty",
    movement: "wander",
  },
  EMPTY_CHAINS: {
    mood: "bored",
    mode: "ambient",
    message: null,
    durationMs: null,
    anchor: "chains-list",
    movement: "wander",
  },
  CHAIN_AVAILABLE: {
    mood: "excited",
    mode: "dialog",
    message: "Нашлась цепочка! Посмотрите новый вариант обмена.",
    durationMs: 4600,
    anchor: "chains-list",
    movement: "run",
  },
  NEW_NOTIFICATION: {
    mood: "excited",
    mode: "dialog",
    message: "Новое уведомление! Оно появилось у колокольчика.",
    durationMs: 4600,
    anchor: "notifications-trigger",
    movement: "run",
  },
  NOTIFICATIONS_PREVIEW_OPENED: {
    mood: "reading",
    mode: "attention",
    message: "Смотрю, что нового…",
    durationMs: null,
    anchor: "notifications-preview",
    movement: "scan",
  },
  NOTIFICATIONS_OPENED: {
    mood: "reading",
    mode: "attention",
    message: "Смотрю, что нового…",
    durationMs: 3800,
    anchor: "notifications-panel",
    movement: "scan",
  },
  NEW_REVIEW: {
    mood: "reading",
    mode: "dialog",
    message: "У вас новый отзыв. Давайте прочитаем его вместе.",
    durationMs: 5200,
    anchor: "latest-review",
    movement: "scan",
  },
  BLOCKED_USER_HOVERED: {
    mood: "angry",
    mode: "attention",
    message: "Плохой! Плохой!",
    durationMs: null,
    anchor: null,
    movement: "kick",
  },
  ERROR: {
    mood: "sad",
    mode: "dialog",
    message: "Похоже, что-то пошло не так. Попробуйте ещё раз.",
    durationMs: 4200,
    anchor: null,
    movement: "roam",
  },
};
