import type { MascotEvent, MascotReaction } from "./mascot.types";

export const mascotReactions: Record<MascotEvent, MascotReaction> = {
  CHAT_OPENED: {
    mood: "idle",
    mode: "dialog",
    message: "Я рядом. Могу подсказать, с чего начать разговор.",
    durationMs: 4200,
    anchor: null,
    movement: "roam",
  },
  USER_TYPING: {
    mood: "listening",
    mode: "ambient",
    message: null,
    durationMs: 1800,
    anchor: null,
    movement: "roam",
  },
  HINT_SHOWN: {
    mood: "hint",
    mode: "attention",
    message: "Не знаете, что написать? Выберите подсказку — текст можно изменить перед отправкой.",
    durationMs: 5200,
    anchor: null,
    movement: "approach",
  },
  HINT_SELECTED: {
    mood: "happy",
    mode: "dialog",
    message: "Отлично! Я вставил текст — проверьте его и отправляйте.",
    durationMs: 3200,
    anchor: null,
    movement: "roam",
  },
  MESSAGE_SENT: {
    mood: "thinking",
    mode: "attention",
    message: "Отправляю…",
    durationMs: 2600,
    anchor: null,
    movement: "roam",
  },
  MESSAGE_SENT_SUCCESS: {
    mood: "happy",
    mode: "attention",
    message: "Сообщение отправлено ✓",
    durationMs: 2200,
    anchor: null,
    movement: "roam",
  },
  MESSAGE_RECEIVED: {
    mood: "happy",
    mode: "attention",
    message: "Есть новый ответ ✨",
    durationMs: 2800,
    anchor: null,
    movement: "run",
  },
  PARTICIPANT_ACCEPTED: {
    mood: "happy",
    mode: "attention",
    message: "Ещё один участник подтвердил обмен.",
    durationMs: 3200,
    anchor: null,
    movement: "run",
  },
  PARTICIPANT_DECLINED: {
    mood: "concerned",
    mode: "dialog",
    message: "Кто-то отказался. Ничего страшного — сервис сможет искать новую цепочку.",
    durationMs: 5200,
    anchor: null,
    movement: "roam",
  },
  PARTICIPANT_DELIVERED: {
    mood: "happy",
    mode: "attention",
    message: "Вещь уже в пункте выдачи. Продвигаемся!",
    durationMs: 3600,
    anchor: null,
    movement: "run",
  },
  EXCHANGE_CONFIRMED: {
    mood: "celebrate",
    mode: "dialog",
    message: "Все подтвердили обмен! 🎉 Теперь можно переходить к передаче вещей.",
    durationMs: 5200,
    anchor: null,
    movement: "run",
  },
  EXCHANGE_DELIVERING: {
    mood: "happy",
    mode: "attention",
    message: "Все вещи приняты — доставка началась.",
    durationMs: 4200,
    anchor: null,
    movement: "run",
  },
  EXCHANGE_DELIVERED: {
    mood: "celebrate",
    mode: "dialog",
    message: "Вещи приехали! Осталось забрать свою в пункте выдачи.",
    durationMs: 5000,
    anchor: null,
    movement: "run",
  },
  EXCHANGE_COMPLETED: {
    mood: "celebrate",
    mode: "dialog",
    message: "Готово! Цепочка обмена успешно завершена 🎉",
    durationMs: 6000,
    anchor: null,
    movement: "run",
  },
  AUTH_FORM_READY: {
    mood: "pointing",
    mode: "attention",
    message: "Заполните форму — кнопка продолжения здесь.",
    durationMs: null,
    anchor: "form-submit",
    movement: "approach",
  },
  FORM_SUBMIT: {
    mood: "thinking",
    mode: "attention",
    message: "Проверяю данные…",
    durationMs: null,
    anchor: "form-submit",
    movement: "approach",
  },
  FORM_SUCCESS: {
    mood: "celebrate",
    mode: "dialog",
    message: "Готово! Всё получилось.",
    durationMs: 4200,
    anchor: "form-submit",
    movement: "run",
  },
  FORM_ERROR: {
    mood: "sad",
    mode: "dialog",
    message: "Не получилось. Проверьте поля и попробуйте ещё раз.",
    durationMs: null,
    anchor: "form-submit",
    movement: "approach",
  },
  EMPTY_ITEMS: {
    mood: "bored",
    mode: "ambient",
    message: null,
    durationMs: null,
    anchor: "items-empty",
    movement: "wander",
  },
  EMPTY_EXCHANGES: {
    mood: "bored",
    mode: "ambient",
    message: null,
    durationMs: null,
    anchor: "exchanges-empty",
    movement: "wander",
  },
  EMPTY_CHAINS: {
    mood: "bored",
    mode: "ambient",
    message: null,
    durationMs: null,
    anchor: "chains-list",
    movement: "wander",
  },
  CHAIN_AVAILABLE: {
    mood: "excited",
    mode: "dialog",
    message: "Нашлась цепочка! Посмотрите новый вариант обмена.",
    durationMs: 4600,
    anchor: "chains-list",
    movement: "run",
  },
  NEW_NOTIFICATION: {
    mood: "excited",
    mode: "dialog",
    message: "Новое уведомление! Оно появилось у колокольчика.",
    durationMs: 4600,
    anchor: "notifications-trigger",
    movement: "run",
  },
  NOTIFICATIONS_OPENED: {
    mood: "reading",
    mode: "attention",
    message: "Смотрю, что нового…",
    durationMs: 3800,
    anchor: "notifications-panel",
    movement: "scan",
  },
  NEW_REVIEW: {
    mood: "reading",
    mode: "dialog",
    message: "У вас новый отзыв. Давайте прочитаем его вместе.",
    durationMs: 5200,
    anchor: "latest-review",
    movement: "scan",
  },
  BLOCKED_USERS_VIEWED: {
    mood: "angry",
    mode: "attention",
    message: "Этим пользователям здесь не место.",
    durationMs: 4800,
    anchor: "blocked-users",
    movement: "kick",
  },
  ERROR: {
    mood: "sad",
    mode: "dialog",
    message: "Похоже, что-то пошло не так. Попробуйте ещё раз.",
    durationMs: 4200,
    anchor: null,
    movement: "roam",
  },
};
