// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockUserForAdmin = `-- name: BlockUserForAdmin :one
WITH changed AS (
    UPDATE users AS account
    SET
        is_blocked = true,
        blocked_at = now(),
        blocked_by = $1
    WHERE account.id = $2
      AND account.id <> $1
      AND NOT account.is_blocked
    RETURNING account.id, account.nickname, account.is_blocked, account.blocked_at, account.blocked_by
), logged AS (
    INSERT INTO admin_audit_log (admin_id, action, target_type, target_id)
    SELECT $1, 'user_blocked', 'user', changed.id
    FROM changed
    RETURNING target_id
)
SELECT changed.id, changed.nickname, changed.is_blocked, changed.blocked_at, changed.blocked_by
FROM changed
JOIN logged ON logged.target_id = changed.id
`

type BlockUserForAdminParams struct {
	AdminID pgtype.UUID
	UserID  pgtype.UUID
}

type BlockUserForAdminRow struct {
	ID        pgtype.UUID
	Nickname  string
	IsBlocked bool
	BlockedAt pgtype.Timestamptz
	BlockedBy pgtype.UUID
}

// Блокировка и запись аудита выполняются одним SQL statement: либо сохранятся обе,
// либо не сохранится ничего. Самого себя администратор заблокировать не может.
func (q *Queries) BlockUserForAdmin(ctx context.Context, arg BlockUserForAdminParams) (BlockUserForAdminRow, error) {
	row := q.db.QueryRow(ctx, blockUserForAdmin, arg.AdminID, arg.UserID)
	var i BlockUserForAdminRow
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.BlockedBy,
	)
	return i, err
}

const canUserAuthenticate = `-- name: CanUserAuthenticate :one
SELECT EXISTS (
    SELECT 1
    FROM users AS account
    WHERE account.id = $1
      AND NOT account.is_blocked
)
`

// Используется middleware на каждом защищённом запросе. Поэтому глобальная
// блокировка немедленно отзывает и уже выданный JWT.
func (q *Queries) CanUserAuthenticate(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, canUserAuthenticate, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAdminAuditLog = `-- name: CountAdminAuditLog :one
SELECT count(*)
FROM admin_audit_log AS log
WHERE ($1::uuid IS NULL OR log.admin_id = $1::uuid)
  AND ($2::text = '' OR log.action::text = $2::text)
  AND ($3::timestamptz IS NULL OR log.created_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR log.created_at <= $4::timestamptz)
`

type CountAdminAuditLogParams struct {
	AdminID  pgtype.UUID
	Action   string
	DateFrom pgtype.Timestamptz
	DateTo   pgtype.Timestamptz
}

func (q *Queries) CountAdminAuditLog(ctx context.Context, arg CountAdminAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminAuditLog,
		arg.AdminID,
		arg.Action,
		arg.DateFrom,
		arg.DateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminAuditLog = `-- name: CreateAdminAuditLog :one
INSERT INTO admin_audit_log (admin_id, action, target_type, target_id, metadata)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, admin_id, action, target_type, target_id, metadata, created_at
`

type CreateAdminAuditLogParams struct {
	AdminID    pgtype.UUID
	Action     AdminAuditAction
	TargetType AdminAuditTarget
	TargetID   pgtype.UUID
	Metadata   []byte
}

func (q *Queries) CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, createAdminAuditLog,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminAuditLog = `-- name: ListAdminAuditLog :many
SELECT log.id, log.admin_id, log.action, log.target_type, log.target_id, log.metadata, log.created_at
FROM admin_audit_log AS log
WHERE ($1::uuid IS NULL OR log.admin_id = $1::uuid)
  AND ($2::text = '' OR log.action::text = $2::text)
  AND ($3::timestamptz IS NULL OR log.created_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR log.created_at <= $4::timestamptz)
ORDER BY log.created_at DESC, log.id DESC
LIMIT $6
OFFSET $5
`

type ListAdminAuditLogParams struct {
	AdminID    pgtype.UUID
	Action     string
	DateFrom   pgtype.Timestamptz
	DateTo     pgtype.Timestamptz
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListAdminAuditLog(ctx context.Context, arg ListAdminAuditLogParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAdminAuditLog,
		arg.AdminID,
		arg.Action,
		arg.DateFrom,
		arg.DateTo,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminAuditLog
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockUserForAdmin = `-- name: UnblockUserForAdmin :one
WITH changed AS (
    UPDATE users AS account
    SET
        is_blocked = false,
        blocked_at = NULL,
        blocked_by = NULL
    WHERE account.id = $1
      AND account.is_blocked
    RETURNING account.id, account.nickname, account.is_blocked, account.blocked_at, account.blocked_by
), logged AS (
    INSERT INTO admin_audit_log (admin_id, action, target_type, target_id)
    SELECT $2, 'user_unblocked', 'user', changed.id
    FROM changed
    RETURNING target_id
)
SELECT changed.id, changed.nickname, changed.is_blocked, changed.blocked_at, changed.blocked_by
FROM changed
JOIN logged ON logged.target_id = changed.id
`

type UnblockUserForAdminParams struct {
	UserID  pgtype.UUID
	AdminID pgtype.UUID
}

type UnblockUserForAdminRow struct {
	ID        pgtype.UUID
	Nickname  string
	IsBlocked bool
	BlockedAt pgtype.Timestamptz
	BlockedBy pgtype.UUID
}

func (q *Queries) UnblockUserForAdmin(ctx context.Context, arg UnblockUserForAdminParams) (UnblockUserForAdminRow, error) {
	row := q.db.QueryRow(ctx, unblockUserForAdmin, arg.UserID, arg.AdminID)
	var i UnblockUserForAdminRow
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.BlockedBy,
	)
	return i, err
}
