// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: antiscam.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAntiscamAnalysis = `-- name: ClaimAntiscamAnalysis :one
WITH candidate AS (
    SELECT analysis.id
    FROM antiscam_analyses AS analysis
    WHERE (
            analysis.status IN ('pending', 'failed')
            AND analysis.available_at <= now()
        )
       OR (
            analysis.status = 'processing'
            AND analysis.locked_at < now() - interval '5 minutes'
        )
    ORDER BY analysis.available_at, analysis.created_at, analysis.id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE antiscam_analyses AS analysis
SET status = 'processing', locked_at = now(), attempts = analysis.attempts + 1
FROM candidate
WHERE analysis.id = candidate.id
RETURNING analysis.id, analysis.message_id, analysis.attempts
`

type ClaimAntiscamAnalysisRow struct {
	ID        pgtype.UUID
	MessageID pgtype.UUID
	Attempts  int32
}

func (q *Queries) ClaimAntiscamAnalysis(ctx context.Context) (ClaimAntiscamAnalysisRow, error) {
	row := q.db.QueryRow(ctx, claimAntiscamAnalysis)
	var i ClaimAntiscamAnalysisRow
	err := row.Scan(&i.ID, &i.MessageID, &i.Attempts)
	return i, err
}

const completeAntiscamAnalysis = `-- name: CompleteAntiscamAnalysis :exec
WITH analyzed AS (
    UPDATE antiscam_analyses
    SET
        status = 'completed',
        locked_at = NULL,
        rule_score = $1,
        rule_hits = $2,
        model_suspicious = $3,
        model_severity = $4,
        category = $5,
        reason = $6,
        evidence = $7,
        risk = $8,
        model_name = $9,
        prompt_version = $10,
        last_error = '',
        processed_at = now()
    WHERE antiscam_analyses.id = $11
    RETURNING antiscam_analyses.message_id
), target AS (
    SELECT message.id AS message_id, message.chain_id, message.author_id
    FROM analyzed
    JOIN chain_messages AS message ON message.id = analyzed.message_id
    WHERE $12::boolean
), opened AS (
    INSERT INTO antiscam_cases (chain_id, suspect_user_id, risk, category, reason)
    SELECT target.chain_id, target.author_id, $8, $5, $6
    FROM target
    ON CONFLICT (chain_id, suspect_user_id) WHERE status = 'open'
    DO UPDATE SET
        risk = greatest(antiscam_cases.risk, excluded.risk),
        category = CASE
            WHEN excluded.risk >= antiscam_cases.risk THEN excluded.category
            ELSE antiscam_cases.category
        END,
        reason = CASE
            WHEN excluded.risk >= antiscam_cases.risk THEN excluded.reason
            ELSE antiscam_cases.reason
        END
    RETURNING id
)
INSERT INTO antiscam_case_messages (case_id, message_id)
SELECT opened.id, target.message_id
FROM opened CROSS JOIN target
ON CONFLICT DO NOTHING
`

type CompleteAntiscamAnalysisParams struct {
	RuleScore       int32
	RuleHits        []string
	ModelSuspicious pgtype.Bool
	ModelSeverity   pgtype.Text
	Category        NullAntiscamCategory
	Reason          string
	Evidence        []string
	Risk            int32
	ModelName       string
	PromptVersion   string
	AnalysisID      pgtype.UUID
	IsSuspicious    bool
}

// Результат анализа и создание/обновление карточки выполняются атомарно.
func (q *Queries) CompleteAntiscamAnalysis(ctx context.Context, arg CompleteAntiscamAnalysisParams) error {
	_, err := q.db.Exec(ctx, completeAntiscamAnalysis,
		arg.RuleScore,
		arg.RuleHits,
		arg.ModelSuspicious,
		arg.ModelSeverity,
		arg.Category,
		arg.Reason,
		arg.Evidence,
		arg.Risk,
		arg.ModelName,
		arg.PromptVersion,
		arg.AnalysisID,
		arg.IsSuspicious,
	)
	return err
}

const countAntiscamCasesForAdmin = `-- name: CountAntiscamCasesForAdmin :one
SELECT count(*)
FROM antiscam_cases AS antiscam_case
WHERE ($1::text = '' OR antiscam_case.status::text = $1::text)
  AND ($2::text = '' OR antiscam_case.category::text = $2::text)
  AND antiscam_case.risk >= $3
`

type CountAntiscamCasesForAdminParams struct {
	CaseStatus   string
	CaseCategory string
	MinRisk      int32
}

func (q *Queries) CountAntiscamCasesForAdmin(ctx context.Context, arg CountAntiscamCasesForAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAntiscamCasesForAdmin, arg.CaseStatus, arg.CaseCategory, arg.MinRisk)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const decideAntiscamCaseForAdmin = `-- name: DecideAntiscamCaseForAdmin :execrows
UPDATE antiscam_cases
SET
    status = CASE
        WHEN $1::text = 'confirmed' THEN 'resolved'::antiscam_case_status
        ELSE 'dismissed'::antiscam_case_status
    END,
    reviewed_by = $2,
    decision = $1,
    resolution_comment = $3,
    closed_at = now()
WHERE id = $4
  AND status = 'open'
`

type DecideAntiscamCaseForAdminParams struct {
	Decision          NullAntiscamDecision
	AdminID           pgtype.UUID
	ResolutionComment string
	CaseID            pgtype.UUID
}

func (q *Queries) DecideAntiscamCaseForAdmin(ctx context.Context, arg DecideAntiscamCaseForAdminParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideAntiscamCaseForAdmin,
		arg.Decision,
		arg.AdminID,
		arg.ResolutionComment,
		arg.CaseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAntiscamCaseForAdmin = `-- name: GetAntiscamCaseForAdmin :one
SELECT
    antiscam_case.id, antiscam_case.chain_id, antiscam_case.suspect_user_id, antiscam_case.status, antiscam_case.risk, antiscam_case.category, antiscam_case.reason, antiscam_case.reviewed_by, antiscam_case.decision, antiscam_case.resolution_comment, antiscam_case.created_at, antiscam_case.updated_at, antiscam_case.closed_at,
    suspect.nickname AS suspect_nickname,
    suspect.photo_url AS suspect_photo_url,
    reviewer.nickname AS reviewer_nickname,
    evidence.message_id AS latest_message_id,
    evidence.body AS latest_message_body,
    evidence.created_at AS latest_message_created_at,
    evidence_count.total AS evidence_count
FROM antiscam_cases AS antiscam_case
JOIN users AS suspect ON suspect.id = antiscam_case.suspect_user_id
LEFT JOIN users AS reviewer ON reviewer.id = antiscam_case.reviewed_by
JOIN LATERAL (
    SELECT message.id AS message_id, message.body, message.created_at
    FROM antiscam_case_messages AS link
    JOIN chain_messages AS message ON message.id = link.message_id
    WHERE link.case_id = antiscam_case.id
    ORDER BY message.created_at DESC, message.id DESC
    LIMIT 1
) AS evidence ON true
JOIN LATERAL (
    SELECT count(*) AS total
    FROM antiscam_case_messages AS link
    WHERE link.case_id = antiscam_case.id
) AS evidence_count ON true
WHERE antiscam_case.id = $1
`

type GetAntiscamCaseForAdminRow struct {
	ID                     pgtype.UUID
	ChainID                pgtype.UUID
	SuspectUserID          pgtype.UUID
	Status                 AntiscamCaseStatus
	Risk                   int32
	Category               AntiscamCategory
	Reason                 string
	ReviewedBy             pgtype.UUID
	Decision               NullAntiscamDecision
	ResolutionComment      string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	ClosedAt               pgtype.Timestamptz
	SuspectNickname        string
	SuspectPhotoUrl        pgtype.Text
	ReviewerNickname       pgtype.Text
	LatestMessageID        pgtype.UUID
	LatestMessageBody      pgtype.Text
	LatestMessageCreatedAt pgtype.Timestamptz
	EvidenceCount          int64
}

func (q *Queries) GetAntiscamCaseForAdmin(ctx context.Context, caseID pgtype.UUID) (GetAntiscamCaseForAdminRow, error) {
	row := q.db.QueryRow(ctx, getAntiscamCaseForAdmin, caseID)
	var i GetAntiscamCaseForAdminRow
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.SuspectUserID,
		&i.Status,
		&i.Risk,
		&i.Category,
		&i.Reason,
		&i.ReviewedBy,
		&i.Decision,
		&i.ResolutionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.SuspectNickname,
		&i.SuspectPhotoUrl,
		&i.ReviewerNickname,
		&i.LatestMessageID,
		&i.LatestMessageBody,
		&i.LatestMessageCreatedAt,
		&i.EvidenceCount,
	)
	return i, err
}

const getAntiscamInput = `-- name: GetAntiscamInput :one
SELECT
    message.id AS message_id,
    message.chain_id,
    message.author_id,
    message.body,
    author.nickname AS author_nickname
FROM chain_messages AS message
JOIN users AS author ON author.id = message.author_id
WHERE message.id = $1
  AND message.kind = 'text'
`

type GetAntiscamInputRow struct {
	MessageID      pgtype.UUID
	ChainID        pgtype.UUID
	AuthorID       pgtype.UUID
	Body           pgtype.Text
	AuthorNickname string
}

func (q *Queries) GetAntiscamInput(ctx context.Context, messageID pgtype.UUID) (GetAntiscamInputRow, error) {
	row := q.db.QueryRow(ctx, getAntiscamInput, messageID)
	var i GetAntiscamInputRow
	err := row.Scan(
		&i.MessageID,
		&i.ChainID,
		&i.AuthorID,
		&i.Body,
		&i.AuthorNickname,
	)
	return i, err
}

const listAntiscamCasesForAdmin = `-- name: ListAntiscamCasesForAdmin :many
SELECT
    antiscam_case.id, antiscam_case.chain_id, antiscam_case.suspect_user_id, antiscam_case.status, antiscam_case.risk, antiscam_case.category, antiscam_case.reason, antiscam_case.reviewed_by, antiscam_case.decision, antiscam_case.resolution_comment, antiscam_case.created_at, antiscam_case.updated_at, antiscam_case.closed_at,
    suspect.nickname AS suspect_nickname,
    suspect.photo_url AS suspect_photo_url,
    reviewer.nickname AS reviewer_nickname,
    evidence.message_id AS latest_message_id,
    evidence.body AS latest_message_body,
    evidence.created_at AS latest_message_created_at,
    evidence_count.total AS evidence_count
FROM antiscam_cases AS antiscam_case
JOIN users AS suspect ON suspect.id = antiscam_case.suspect_user_id
LEFT JOIN users AS reviewer ON reviewer.id = antiscam_case.reviewed_by
JOIN LATERAL (
    SELECT message.id AS message_id, message.body, message.created_at
    FROM antiscam_case_messages AS link
    JOIN chain_messages AS message ON message.id = link.message_id
    WHERE link.case_id = antiscam_case.id
    ORDER BY message.created_at DESC, message.id DESC
    LIMIT 1
) AS evidence ON true
JOIN LATERAL (
    SELECT count(*) AS total
    FROM antiscam_case_messages AS link
    WHERE link.case_id = antiscam_case.id
) AS evidence_count ON true
WHERE ($1::text = '' OR antiscam_case.status::text = $1::text)
  AND ($2::text = '' OR antiscam_case.category::text = $2::text)
  AND antiscam_case.risk >= $3
ORDER BY antiscam_case.risk DESC, antiscam_case.updated_at DESC, antiscam_case.id DESC
LIMIT $5
OFFSET $4
`

type ListAntiscamCasesForAdminParams struct {
	CaseStatus   string
	CaseCategory string
	MinRisk      int32
	PageOffset   int32
	PageLimit    int32
}

type ListAntiscamCasesForAdminRow struct {
	ID                     pgtype.UUID
	ChainID                pgtype.UUID
	SuspectUserID          pgtype.UUID
	Status                 AntiscamCaseStatus
	Risk                   int32
	Category               AntiscamCategory
	Reason                 string
	ReviewedBy             pgtype.UUID
	Decision               NullAntiscamDecision
	ResolutionComment      string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	ClosedAt               pgtype.Timestamptz
	SuspectNickname        string
	SuspectPhotoUrl        pgtype.Text
	ReviewerNickname       pgtype.Text
	LatestMessageID        pgtype.UUID
	LatestMessageBody      pgtype.Text
	LatestMessageCreatedAt pgtype.Timestamptz
	EvidenceCount          int64
}

func (q *Queries) ListAntiscamCasesForAdmin(ctx context.Context, arg ListAntiscamCasesForAdminParams) ([]ListAntiscamCasesForAdminRow, error) {
	rows, err := q.db.Query(ctx, listAntiscamCasesForAdmin,
		arg.CaseStatus,
		arg.CaseCategory,
		arg.MinRisk,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAntiscamCasesForAdminRow
	for rows.Next() {
		var i ListAntiscamCasesForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.SuspectUserID,
			&i.Status,
			&i.Risk,
			&i.Category,
			&i.Reason,
			&i.ReviewedBy,
			&i.Decision,
			&i.ResolutionComment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.SuspectNickname,
			&i.SuspectPhotoUrl,
			&i.ReviewerNickname,
			&i.LatestMessageID,
			&i.LatestMessageBody,
			&i.LatestMessageCreatedAt,
			&i.EvidenceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAntiscamContext = `-- name: ListAntiscamContext :many
SELECT
    message.id,
    message.author_id,
    author.nickname,
    message.body,
    message.created_at
FROM chain_messages AS target
JOIN chain_messages AS message
    ON message.chain_id = target.chain_id
   AND message.kind = 'text'
   AND (message.created_at, message.id) <= (target.created_at, target.id)
JOIN users AS author ON author.id = message.author_id
WHERE target.id = $1
ORDER BY message.created_at DESC, message.id DESC
LIMIT 6
`

type ListAntiscamContextRow struct {
	ID        pgtype.UUID
	AuthorID  pgtype.UUID
	Nickname  string
	Body      pgtype.Text
	CreatedAt pgtype.Timestamptz
}

// Последние реплики до проверяемой включительно. Разворачивает их repository,
// чтобы модель увидела диалог в обычном хронологическом порядке.
func (q *Queries) ListAntiscamContext(ctx context.Context, messageID pgtype.UUID) ([]ListAntiscamContextRow, error) {
	rows, err := q.db.Query(ctx, listAntiscamContext, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAntiscamContextRow
	for rows.Next() {
		var i ListAntiscamContextRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Nickname,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAntiscamEvidenceIDs = `-- name: ListAntiscamEvidenceIDs :many
SELECT message_id
FROM antiscam_case_messages
WHERE case_id = $1
ORDER BY created_at, message_id
`

func (q *Queries) ListAntiscamEvidenceIDs(ctx context.Context, caseID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAntiscamEvidenceIDs, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var message_id pgtype.UUID
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryAntiscamAnalysis = `-- name: RetryAntiscamAnalysis :exec
UPDATE antiscam_analyses
SET
    status = 'failed',
    locked_at = NULL,
    available_at = now() + make_interval(secs => $1::integer),
    last_error = left($2, 2000)
WHERE id = $3
`

type RetryAntiscamAnalysisParams struct {
	RetrySeconds int32
	LastError    string
	AnalysisID   pgtype.UUID
}

func (q *Queries) RetryAntiscamAnalysis(ctx context.Context, arg RetryAntiscamAnalysisParams) error {
	_, err := q.db.Exec(ctx, retryAntiscamAnalysis, arg.RetrySeconds, arg.LastError, arg.AnalysisID)
	return err
}
