// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chain_messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChainMessage = `-- name: CreateChainMessage :one
WITH inserted AS (
    INSERT INTO chain_messages (chain_id, author_id, body)
    VALUES ($1, $2, $3)
    RETURNING id, kind, body, created_at, author_id
), queued AS (
    INSERT INTO antiscam_analyses (message_id)
    SELECT inserted.id FROM inserted
    RETURNING message_id
)
SELECT
    inserted.id,
    inserted.kind,
    inserted.body,
    inserted.created_at,
    inserted.author_id,
    author.nickname  AS author_nickname,
    author.photo_url AS author_photo_url
FROM inserted
JOIN queued ON queued.message_id = inserted.id
LEFT JOIN users AS author
    ON author.id = inserted.author_id
`

type CreateChainMessageParams struct {
	ExchangeID pgtype.UUID
	AuthorID   pgtype.UUID
	Body       pgtype.Text
}

type CreateChainMessageRow struct {
	ID             pgtype.UUID
	Kind           ChainMessageKind
	Body           pgtype.Text
	CreatedAt      pgtype.Timestamptz
	AuthorID       pgtype.UUID
	AuthorNickname pgtype.Text
	AuthorPhotoUrl pgtype.Text
}

// Отправитель получает назад ровно ту же форму сообщения, что придёт следующим
// чтением треда, поэтому RETURNING идёт через CTE с автором. LEFT JOIN здесь не ради
// NULL-автора (у текста он обязателен), а чтобы тип строки совпал с ListChainMessages.
func (q *Queries) CreateChainMessage(ctx context.Context, arg CreateChainMessageParams) (CreateChainMessageRow, error) {
	row := q.db.QueryRow(ctx, createChainMessage, arg.ExchangeID, arg.AuthorID, arg.Body)
	var i CreateChainMessageRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Body,
		&i.CreatedAt,
		&i.AuthorID,
		&i.AuthorNickname,
		&i.AuthorPhotoUrl,
	)
	return i, err
}

const createChainSystemMessage = `-- name: CreateChainSystemMessage :exec
INSERT INTO chain_messages (chain_id, author_id, kind)
VALUES ($1, $2, $3)
`

type CreateChainSystemMessageParams struct {
	ExchangeID pgtype.UUID
	AuthorID   pgtype.UUID
	Kind       ChainMessageKind
}

// Событие сделки. author_id остаётся NULL, если событие принадлежит всему обмену,
// а не конкретному участнику. body у событий пустой — текст собирает frontend.
func (q *Queries) CreateChainSystemMessage(ctx context.Context, arg CreateChainSystemMessageParams) error {
	_, err := q.db.Exec(ctx, createChainSystemMessage, arg.ExchangeID, arg.AuthorID, arg.Kind)
	return err
}

const getExchangeAccess = `-- name: GetExchangeAccess :one
SELECT
    exchange.status,
    EXISTS (
        SELECT 1
        FROM chain_participants AS participant
        WHERE participant.chain_id = exchange.id
          AND participant.user_id = $1
    ) AS is_participant
FROM chains AS exchange
WHERE exchange.id = $2
`

type GetExchangeAccessParams struct {
	UserID     pgtype.UUID
	ExchangeID pgtype.UUID
}

type GetExchangeAccessRow struct {
	Status        ChainStatus
	IsParticipant bool
}

// Доступ к треду: существование обмена, участие пользователя и статус — за один запрос.
// Полный JOIN из GetExchangeByID ради проверки прав дёргать незачем.
func (q *Queries) GetExchangeAccess(ctx context.Context, arg GetExchangeAccessParams) (GetExchangeAccessRow, error) {
	row := q.db.QueryRow(ctx, getExchangeAccess, arg.UserID, arg.ExchangeID)
	var i GetExchangeAccessRow
	err := row.Scan(&i.Status, &i.IsParticipant)
	return i, err
}

const listChainMessages = `-- name: ListChainMessages :many
SELECT
    message.id,
    message.kind,
    message.body,
    message.created_at,
    message.author_id,
    author.nickname  AS author_nickname,
    author.photo_url AS author_photo_url
FROM chain_messages AS message
LEFT JOIN users AS author
    ON author.id = message.author_id
WHERE message.chain_id = $1
ORDER BY message.created_at, message.id
`

type ListChainMessagesRow struct {
	ID             pgtype.UUID
	Kind           ChainMessageKind
	Body           pgtype.Text
	CreatedAt      pgtype.Timestamptz
	AuthorID       pgtype.UUID
	AuthorNickname pgtype.Text
	AuthorPhotoUrl pgtype.Text
}

// LEFT JOIN: у событий обмена автора нет.
func (q *Queries) ListChainMessages(ctx context.Context, exchangeID pgtype.UUID) ([]ListChainMessagesRow, error) {
	rows, err := q.db.Query(ctx, listChainMessages, exchangeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChainMessagesRow
	for rows.Next() {
		var i ListChainMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorNickname,
			&i.AuthorPhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChainMessagesRead = `-- name: MarkChainMessagesRead :exec
UPDATE chain_participants
SET messages_read_at = greatest(
        messages_read_at,
        (
            SELECT message.created_at
            FROM chain_messages AS message
            WHERE message.id = $1
              AND message.chain_id = $2
        )
    )
WHERE chain_id = $2
  AND user_id = $3
`

type MarkChainMessagesReadParams struct {
	LastMessageID pgtype.UUID
	ExchangeID    pgtype.UUID
	UserID        pgtype.UUID
}

// Отметка ставится по последнему сообщению, которое клиент реально показал: время берётся
// из самой строки треда, а не с часов сервера. Поэтому сообщение, попавшее в базу уже после
// ответа на чтение, пометить прочитанным невозможно, и обе метки по построению лежат в одной
// шкале. greatest() делает вызов монотонным и идемпотентным: повтор, две открытые вкладки и
// id из чужого треда ничего не сдвигают назад, потому что greatest игнорирует NULL.
func (q *Queries) MarkChainMessagesRead(ctx context.Context, arg MarkChainMessagesReadParams) error {
	_, err := q.db.Exec(ctx, markChainMessagesRead, arg.LastMessageID, arg.ExchangeID, arg.UserID)
	return err
}
