// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_read.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveExchangesForAdmin = `-- name: CountActiveExchangesForAdmin :one
SELECT count(*)
FROM chains AS exchange
WHERE exchange.status IN ('proposed', 'confirmed', 'delivering', 'delivered')
  AND (
      $1::uuid IS NULL
      OR EXISTS (
          SELECT 1
          FROM chain_participants AS selected_participant
          WHERE selected_participant.chain_id = exchange.id
            AND selected_participant.user_id = $1::uuid
      )
  )
  AND (
      $2::text = ''
      OR exchange.status::text = $2::text
  )
`

type CountActiveExchangesForAdminParams struct {
	UserID         pgtype.UUID
	ExchangeStatus string
}

func (q *Queries) CountActiveExchangesForAdmin(ctx context.Context, arg CountActiveExchangesForAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveExchangesForAdmin, arg.UserID, arg.ExchangeStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getExchangeByID = `-- name: GetExchangeByID :many
SELECT
    exchange.id          AS exchange_id,
    exchange.status      AS exchange_status,
    exchange.created_at  AS exchange_created_at,
    exchange.updated_at  AS exchange_updated_at,
    exchange.closed_at   AS exchange_closed_at,
    participant.user_id,
    participant.position,
    participant.status   AS participant_status,
    participant.decided_at,
    participant.completion_confirmed_at,
    exchange_user.nickname,
    exchange_user.photo_url AS user_photo_url,
    gives_item.id          AS gives_item_id,
    gives_item.title       AS gives_item_title,
    gives_item.description AS gives_item_description,
    gives_item.status      AS gives_item_status,
    gives_category.slug    AS gives_category_slug,
    gives_category.name    AS gives_category_name,
    gives_pickup.id        AS gives_pickup_point_id,
    gives_pickup.name      AS gives_pickup_point_name,
    gives_pickup.address   AS gives_pickup_point_address,
    receives_item.id          AS receives_item_id,
    receives_item.title       AS receives_item_title,
    receives_item.description AS receives_item_description,
    receives_item.status      AS receives_item_status,
    receives_category.slug    AS receives_category_slug,
    receives_category.name    AS receives_category_name,
    receives_pickup.id        AS receives_pickup_point_id,
    receives_pickup.name      AS receives_pickup_point_name,
    receives_pickup.address   AS receives_pickup_point_address,
    (
        SELECT count(*)
        FROM chain_messages AS unread
        WHERE unread.chain_id = exchange.id
          AND unread.created_at > coalesce(current_participant.messages_read_at, '-infinity')
          AND unread.author_id IS DISTINCT FROM $1
    ) AS unread_count
FROM chains AS exchange
LEFT JOIN chain_participants AS current_participant
    ON current_participant.chain_id = exchange.id
   AND current_participant.user_id = $1
JOIN chain_participants AS participant
    ON participant.chain_id = exchange.id
JOIN users AS exchange_user
    ON exchange_user.id = participant.user_id
JOIN items AS gives_item
    ON gives_item.id = participant.gives_item_id
JOIN categories AS gives_category
    ON gives_category.id = gives_item.category_id
LEFT JOIN pickup_points AS gives_pickup
    ON gives_pickup.id = gives_item.pickup_point_id
JOIN items AS receives_item
    ON receives_item.id = participant.receives_item_id
JOIN categories AS receives_category
    ON receives_category.id = receives_item.category_id
LEFT JOIN pickup_points AS receives_pickup
    ON receives_pickup.id = receives_item.pickup_point_id
WHERE exchange.id = $2
ORDER BY participant.position
`

type GetExchangeByIDParams struct {
	UserID     pgtype.UUID
	ExchangeID pgtype.UUID
}

type GetExchangeByIDRow struct {
	ExchangeID                 pgtype.UUID
	ExchangeStatus             ChainStatus
	ExchangeCreatedAt          pgtype.Timestamptz
	ExchangeUpdatedAt          pgtype.Timestamptz
	ExchangeClosedAt           pgtype.Timestamptz
	UserID                     pgtype.UUID
	Position                   int32
	ParticipantStatus          ParticipantStatus
	DecidedAt                  pgtype.Timestamptz
	CompletionConfirmedAt      pgtype.Timestamptz
	Nickname                   string
	UserPhotoUrl               pgtype.Text
	GivesItemID                pgtype.UUID
	GivesItemTitle             string
	GivesItemDescription       string
	GivesItemStatus            ItemStatus
	GivesCategorySlug          string
	GivesCategoryName          string
	GivesPickupPointID         pgtype.UUID
	GivesPickupPointName       pgtype.Text
	GivesPickupPointAddress    pgtype.Text
	ReceivesItemID             pgtype.UUID
	ReceivesItemTitle          string
	ReceivesItemDescription    string
	ReceivesItemStatus         ItemStatus
	ReceivesCategorySlug       string
	ReceivesCategoryName       string
	ReceivesPickupPointID      pgtype.UUID
	ReceivesPickupPointName    pgtype.Text
	ReceivesPickupPointAddress pgtype.Text
	UnreadCount                int64
}

// LEFT JOIN, в отличие от списка: обмен обязан вернуться и постороннему, иначе сервис
// ответил бы «не найден» вместо «нельзя смотреть». Счётчик для него всё равно не поедет.
// LEFT: вещь дома пункта не имеет, INNER выбросил бы её участника из ответа целиком.
func (q *Queries) GetExchangeByID(ctx context.Context, arg GetExchangeByIDParams) ([]GetExchangeByIDRow, error) {
	rows, err := q.db.Query(ctx, getExchangeByID, arg.UserID, arg.ExchangeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExchangeByIDRow
	for rows.Next() {
		var i GetExchangeByIDRow
		if err := rows.Scan(
			&i.ExchangeID,
			&i.ExchangeStatus,
			&i.ExchangeCreatedAt,
			&i.ExchangeUpdatedAt,
			&i.ExchangeClosedAt,
			&i.UserID,
			&i.Position,
			&i.ParticipantStatus,
			&i.DecidedAt,
			&i.CompletionConfirmedAt,
			&i.Nickname,
			&i.UserPhotoUrl,
			&i.GivesItemID,
			&i.GivesItemTitle,
			&i.GivesItemDescription,
			&i.GivesItemStatus,
			&i.GivesCategorySlug,
			&i.GivesCategoryName,
			&i.GivesPickupPointID,
			&i.GivesPickupPointName,
			&i.GivesPickupPointAddress,
			&i.ReceivesItemID,
			&i.ReceivesItemTitle,
			&i.ReceivesItemDescription,
			&i.ReceivesItemStatus,
			&i.ReceivesCategorySlug,
			&i.ReceivesCategoryName,
			&i.ReceivesPickupPointID,
			&i.ReceivesPickupPointName,
			&i.ReceivesPickupPointAddress,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveExchangesForAdmin = `-- name: ListActiveExchangesForAdmin :many
WITH selected_exchanges AS (
    SELECT exchange.id, exchange.created_at
    FROM chains AS exchange
    WHERE exchange.status IN ('proposed', 'confirmed', 'delivering', 'delivered')
      AND (
          $1::uuid IS NULL
          OR EXISTS (
              SELECT 1
              FROM chain_participants AS selected_participant
              WHERE selected_participant.chain_id = exchange.id
                AND selected_participant.user_id = $1::uuid
          )
      )
      AND (
          $2::text = ''
          OR exchange.status::text = $2::text
      )
    ORDER BY exchange.created_at DESC, exchange.id
    LIMIT $4
    OFFSET $3
)
SELECT
    exchange.id          AS exchange_id,
    exchange.status      AS exchange_status,
    exchange.created_at  AS exchange_created_at,
    exchange.updated_at  AS exchange_updated_at,
    exchange.closed_at   AS exchange_closed_at,
    participant.user_id,
    participant.position,
    participant.status   AS participant_status,
    participant.decided_at,
    participant.completion_confirmed_at,
    exchange_user.nickname,
    exchange_user.photo_url AS user_photo_url,
    gives_item.id          AS gives_item_id,
    gives_item.title       AS gives_item_title,
    gives_item.description AS gives_item_description,
    gives_item.status      AS gives_item_status,
    gives_category.slug    AS gives_category_slug,
    gives_category.name    AS gives_category_name,
    gives_pickup.id        AS gives_pickup_point_id,
    gives_pickup.name      AS gives_pickup_point_name,
    gives_pickup.address   AS gives_pickup_point_address,
    receives_item.id          AS receives_item_id,
    receives_item.title       AS receives_item_title,
    receives_item.description AS receives_item_description,
    receives_item.status      AS receives_item_status,
    receives_category.slug    AS receives_category_slug,
    receives_category.name    AS receives_category_name,
    receives_pickup.id        AS receives_pickup_point_id,
    receives_pickup.name      AS receives_pickup_point_name,
    receives_pickup.address   AS receives_pickup_point_address,
    0::bigint AS unread_count
FROM selected_exchanges AS selected
JOIN chains AS exchange
    ON exchange.id = selected.id
JOIN chain_participants AS participant
    ON participant.chain_id = exchange.id
JOIN users AS exchange_user
    ON exchange_user.id = participant.user_id
JOIN items AS gives_item
    ON gives_item.id = participant.gives_item_id
JOIN categories AS gives_category
    ON gives_category.id = gives_item.category_id
LEFT JOIN pickup_points AS gives_pickup
    ON gives_pickup.id = gives_item.pickup_point_id
JOIN items AS receives_item
    ON receives_item.id = participant.receives_item_id
JOIN categories AS receives_category
    ON receives_category.id = receives_item.category_id
LEFT JOIN pickup_points AS receives_pickup
    ON receives_pickup.id = receives_item.pickup_point_id
ORDER BY exchange.created_at DESC, exchange.id, participant.position
`

type ListActiveExchangesForAdminParams struct {
	UserID         pgtype.UUID
	ExchangeStatus string
	PageOffset     int32
	PageLimit      int32
}

type ListActiveExchangesForAdminRow struct {
	ExchangeID                 pgtype.UUID
	ExchangeStatus             ChainStatus
	ExchangeCreatedAt          pgtype.Timestamptz
	ExchangeUpdatedAt          pgtype.Timestamptz
	ExchangeClosedAt           pgtype.Timestamptz
	UserID                     pgtype.UUID
	Position                   int32
	ParticipantStatus          ParticipantStatus
	DecidedAt                  pgtype.Timestamptz
	CompletionConfirmedAt      pgtype.Timestamptz
	Nickname                   string
	UserPhotoUrl               pgtype.Text
	GivesItemID                pgtype.UUID
	GivesItemTitle             string
	GivesItemDescription       string
	GivesItemStatus            ItemStatus
	GivesCategorySlug          string
	GivesCategoryName          string
	GivesPickupPointID         pgtype.UUID
	GivesPickupPointName       pgtype.Text
	GivesPickupPointAddress    pgtype.Text
	ReceivesItemID             pgtype.UUID
	ReceivesItemTitle          string
	ReceivesItemDescription    string
	ReceivesItemStatus         ItemStatus
	ReceivesCategorySlug       string
	ReceivesCategoryName       string
	ReceivesPickupPointID      pgtype.UUID
	ReceivesPickupPointName    pgtype.Text
	ReceivesPickupPointAddress pgtype.Text
	UnreadCount                int64
}

// Общий список для администратора: существующая ручка фильтрует его по user_id,
// очередь доставки — по status. Пустой status означает любой активный этап.
// LEFT: вещь дома пункта не имеет, INNER выбросил бы её участника из ответа целиком.
func (q *Queries) ListActiveExchangesForAdmin(ctx context.Context, arg ListActiveExchangesForAdminParams) ([]ListActiveExchangesForAdminRow, error) {
	rows, err := q.db.Query(ctx, listActiveExchangesForAdmin,
		arg.UserID,
		arg.ExchangeStatus,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveExchangesForAdminRow
	for rows.Next() {
		var i ListActiveExchangesForAdminRow
		if err := rows.Scan(
			&i.ExchangeID,
			&i.ExchangeStatus,
			&i.ExchangeCreatedAt,
			&i.ExchangeUpdatedAt,
			&i.ExchangeClosedAt,
			&i.UserID,
			&i.Position,
			&i.ParticipantStatus,
			&i.DecidedAt,
			&i.CompletionConfirmedAt,
			&i.Nickname,
			&i.UserPhotoUrl,
			&i.GivesItemID,
			&i.GivesItemTitle,
			&i.GivesItemDescription,
			&i.GivesItemStatus,
			&i.GivesCategorySlug,
			&i.GivesCategoryName,
			&i.GivesPickupPointID,
			&i.GivesPickupPointName,
			&i.GivesPickupPointAddress,
			&i.ReceivesItemID,
			&i.ReceivesItemTitle,
			&i.ReceivesItemDescription,
			&i.ReceivesItemStatus,
			&i.ReceivesCategorySlug,
			&i.ReceivesCategoryName,
			&i.ReceivesPickupPointID,
			&i.ReceivesPickupPointName,
			&i.ReceivesPickupPointAddress,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExchangesByUser = `-- name: ListExchangesByUser :many
SELECT
    exchange.id          AS exchange_id,
    exchange.status      AS exchange_status,
    exchange.created_at  AS exchange_created_at,
    exchange.updated_at  AS exchange_updated_at,
    exchange.closed_at   AS exchange_closed_at,
    participant.user_id,
    participant.position,
    participant.status   AS participant_status,
    participant.decided_at,
    participant.completion_confirmed_at,
    exchange_user.nickname,
    exchange_user.photo_url AS user_photo_url,
    gives_item.id          AS gives_item_id,
    gives_item.title       AS gives_item_title,
    gives_item.description AS gives_item_description,
    gives_item.status      AS gives_item_status,
    gives_category.slug    AS gives_category_slug,
    gives_category.name    AS gives_category_name,
    gives_pickup.id        AS gives_pickup_point_id,
    gives_pickup.name      AS gives_pickup_point_name,
    gives_pickup.address   AS gives_pickup_point_address,
    receives_item.id          AS receives_item_id,
    receives_item.title       AS receives_item_title,
    receives_item.description AS receives_item_description,
    receives_item.status      AS receives_item_status,
    receives_category.slug    AS receives_category_slug,
    receives_category.name    AS receives_category_name,
    receives_pickup.id        AS receives_pickup_point_id,
    receives_pickup.name      AS receives_pickup_point_name,
    receives_pickup.address   AS receives_pickup_point_address,
    (
        SELECT count(*)
        FROM chain_messages AS unread
        WHERE unread.chain_id = exchange.id
          AND unread.created_at > coalesce(current_participant.messages_read_at, '-infinity')
          -- IS DISTINCT FROM, а не <>: у событий обмена автора нет, и они тоже считаются
          -- непрочитанными — ради них счётчик в основном и нужен.
          AND unread.author_id IS DISTINCT FROM $1
    ) AS unread_count
FROM chains AS exchange
JOIN chain_participants AS current_participant
    ON current_participant.chain_id = exchange.id
   AND current_participant.user_id = $1
JOIN chain_participants AS participant
    ON participant.chain_id = exchange.id
JOIN users AS exchange_user
    ON exchange_user.id = participant.user_id
JOIN items AS gives_item
    ON gives_item.id = participant.gives_item_id
JOIN categories AS gives_category
    ON gives_category.id = gives_item.category_id
LEFT JOIN pickup_points AS gives_pickup
    ON gives_pickup.id = gives_item.pickup_point_id
JOIN items AS receives_item
    ON receives_item.id = participant.receives_item_id
JOIN categories AS receives_category
    ON receives_category.id = receives_item.category_id
LEFT JOIN pickup_points AS receives_pickup
    ON receives_pickup.id = receives_item.pickup_point_id
ORDER BY exchange.created_at DESC, exchange.id, participant.position
`

type ListExchangesByUserRow struct {
	ExchangeID                 pgtype.UUID
	ExchangeStatus             ChainStatus
	ExchangeCreatedAt          pgtype.Timestamptz
	ExchangeUpdatedAt          pgtype.Timestamptz
	ExchangeClosedAt           pgtype.Timestamptz
	UserID                     pgtype.UUID
	Position                   int32
	ParticipantStatus          ParticipantStatus
	DecidedAt                  pgtype.Timestamptz
	CompletionConfirmedAt      pgtype.Timestamptz
	Nickname                   string
	UserPhotoUrl               pgtype.Text
	GivesItemID                pgtype.UUID
	GivesItemTitle             string
	GivesItemDescription       string
	GivesItemStatus            ItemStatus
	GivesCategorySlug          string
	GivesCategoryName          string
	GivesPickupPointID         pgtype.UUID
	GivesPickupPointName       pgtype.Text
	GivesPickupPointAddress    pgtype.Text
	ReceivesItemID             pgtype.UUID
	ReceivesItemTitle          string
	ReceivesItemDescription    string
	ReceivesItemStatus         ItemStatus
	ReceivesCategorySlug       string
	ReceivesCategoryName       string
	ReceivesPickupPointID      pgtype.UUID
	ReceivesPickupPointName    pgtype.Text
	ReceivesPickupPointAddress pgtype.Text
	UnreadCount                int64
}

// Все участники нужны frontend, поэтому текущего пользователя подмешиваем отдельным
// JOIN: основной JOIN оставил бы в ответе только его строку. UNIQUE (chain_id, user_id)
// гарантирует, что этот JOIN даёт ровно одну строку и не размножает участников,
// а заодно открывает доступ к его отметке о прочтении треда.
// LEFT: вещь дома пункта не имеет, INNER выбросил бы её участника из ответа целиком.
func (q *Queries) ListExchangesByUser(ctx context.Context, userID pgtype.UUID) ([]ListExchangesByUserRow, error) {
	rows, err := q.db.Query(ctx, listExchangesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExchangesByUserRow
	for rows.Next() {
		var i ListExchangesByUserRow
		if err := rows.Scan(
			&i.ExchangeID,
			&i.ExchangeStatus,
			&i.ExchangeCreatedAt,
			&i.ExchangeUpdatedAt,
			&i.ExchangeClosedAt,
			&i.UserID,
			&i.Position,
			&i.ParticipantStatus,
			&i.DecidedAt,
			&i.CompletionConfirmedAt,
			&i.Nickname,
			&i.UserPhotoUrl,
			&i.GivesItemID,
			&i.GivesItemTitle,
			&i.GivesItemDescription,
			&i.GivesItemStatus,
			&i.GivesCategorySlug,
			&i.GivesCategoryName,
			&i.GivesPickupPointID,
			&i.GivesPickupPointName,
			&i.GivesPickupPointAddress,
			&i.ReceivesItemID,
			&i.ReceivesItemTitle,
			&i.ReceivesItemDescription,
			&i.ReceivesItemStatus,
			&i.ReceivesCategorySlug,
			&i.ReceivesCategoryName,
			&i.ReceivesPickupPointID,
			&i.ReceivesPickupPointName,
			&i.ReceivesPickupPointAddress,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
