// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_decision.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptExchangeParticipant = `-- name: AcceptExchangeParticipant :exec
UPDATE chain_participants
SET status = 'accepted',
    decided_at = now()
WHERE chain_id = $1
  AND user_id = $2
`

type AcceptExchangeParticipantParams struct {
	ExchangeID pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) AcceptExchangeParticipant(ctx context.Context, arg AcceptExchangeParticipantParams) error {
	_, err := q.db.Exec(ctx, acceptExchangeParticipant, arg.ExchangeID, arg.UserID)
	return err
}

const cancelCompetingProposedExchanges = `-- name: CancelCompetingProposedExchanges :execrows
WITH current_items AS (
    SELECT participant.gives_item_id AS item_id
    FROM chain_participants AS participant
    WHERE participant.chain_id = $1
    UNION
    SELECT participant.receives_item_id AS item_id
    FROM chain_participants AS participant
    WHERE participant.chain_id = $1
), cancelled AS (
    UPDATE chains AS competing_exchange
    SET status = 'cancelled',
        closed_at = now(),
        cancel_reason = 'superseded'
    WHERE competing_exchange.id <> $1
      AND competing_exchange.status = 'proposed'
      AND EXISTS (
          SELECT 1
          FROM chain_participants AS competing_participant
          JOIN current_items
            ON current_items.item_id = competing_participant.gives_item_id
            OR current_items.item_id = competing_participant.receives_item_id
          WHERE competing_participant.chain_id = competing_exchange.id
      )
    RETURNING competing_exchange.id
)
INSERT INTO chain_messages (chain_id, kind)
SELECT cancelled.id, 'exchange_superseded'
FROM cancelled
`

// После победы одного обмена все ещё открытые предложения с любым общим
// объявлением больше не выполнимы и сразу закрываются для frontend. Отмена и запись
// события в тред каждой отменённой цепочки — одно выражение: участник не может
// увидеть закрытый обмен без объяснения, почему он закрылся.
func (q *Queries) CancelCompetingProposedExchanges(ctx context.Context, exchangeID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelCompetingProposedExchanges, exchangeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelExchange = `-- name: CancelExchange :exec
UPDATE chains
SET status = 'cancelled',
    closed_at = now(),
    cancel_reason = $1::chain_cancel_reason
WHERE id = $2
  AND status <> 'cancelled'
`

type CancelExchangeParams struct {
	CancelReason ChainCancelReason
	ExchangeID   pgtype.UUID
}

func (q *Queries) CancelExchange(ctx context.Context, arg CancelExchangeParams) error {
	_, err := q.db.Exec(ctx, cancelExchange, arg.CancelReason, arg.ExchangeID)
	return err
}

const confirmExchange = `-- name: ConfirmExchange :exec
UPDATE chains
SET status = 'confirmed'
WHERE id = $1
`

func (q *Queries) ConfirmExchange(ctx context.Context, exchangeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, confirmExchange, exchangeID)
	return err
}

const countPendingExchangeParticipants = `-- name: CountPendingExchangeParticipants :one
SELECT count(*)
FROM chain_participants
WHERE chain_id = $1
  AND status = 'pending'
`

func (q *Queries) CountPendingExchangeParticipants(ctx context.Context, exchangeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingExchangeParticipants, exchangeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const declineExchangeParticipant = `-- name: DeclineExchangeParticipant :exec
UPDATE chain_participants
SET status = 'declined',
    decided_at = now()
WHERE chain_id = $1
  AND user_id = $2
`

type DeclineExchangeParticipantParams struct {
	ExchangeID pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) DeclineExchangeParticipant(ctx context.Context, arg DeclineExchangeParticipantParams) error {
	_, err := q.db.Exec(ctx, declineExchangeParticipant, arg.ExchangeID, arg.UserID)
	return err
}

const findConfirmedExchangeForItem = `-- name: FindConfirmedExchangeForItem :one
SELECT exchange.id
FROM chains AS exchange
JOIN chain_participants AS participant ON participant.chain_id = exchange.id
WHERE participant.gives_item_id = $1
  AND exchange.status = 'confirmed'
`

// Вещь может лежать в нескольких предложенных обменах, но подтверждённый у неё ровно
// один: подтверждение резервирует её вещи и гасит конкурентов. Поэтому :one, а pgx.ErrNoRows
// здесь — нормальный ответ «вещь ни в каком подтверждённом обмене не участвует».
func (q *Queries) FindConfirmedExchangeForItem(ctx context.Context, itemID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findConfirmedExchangeForItem, itemID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const incrementUserDealsBroken = `-- name: IncrementUserDealsBroken :execrows
UPDATE users
SET deals_broken = deals_broken + 1
WHERE id = $1
`

// deals_broken показывает, сколько уже подтверждённых обменов сорвал пользователь.
// Отказ от ещё не подтверждённого предложения в этот счётчик не входит.
func (q *Queries) IncrementUserDealsBroken(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incrementUserDealsBroken, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockExchange = `-- name: LockExchange :one
SELECT status, signature, composition_key
FROM chains
WHERE id = $1
FOR UPDATE
`

type LockExchangeRow struct {
	Status         ChainStatus
	Signature      string
	CompositionKey string
}

// Строка обмена блокируется первой. Поэтому два одновременных решения по одному
// обмену выполняются последовательно и не могут потерять обновления друг друга.
func (q *Queries) LockExchange(ctx context.Context, exchangeID pgtype.UUID) (LockExchangeRow, error) {
	row := q.db.QueryRow(ctx, lockExchange, exchangeID)
	var i LockExchangeRow
	err := row.Scan(&i.Status, &i.Signature, &i.CompositionKey)
	return i, err
}

const lockExchangeDecisionItems = `-- name: LockExchangeDecisionItems :exec
SELECT pg_advisory_xact_lock(hashtextextended(exchange_item.item_id::text, 0))
FROM (
    SELECT participant.gives_item_id AS item_id
    FROM chain_participants AS participant
    WHERE participant.chain_id = $1
    UNION
    SELECT participant.receives_item_id AS item_id
    FROM chain_participants AS participant
    WHERE participant.chain_id = $1
) AS exchange_item
ORDER BY exchange_item.item_id
`

// Все операции принятия решения сначала блокируют объявления обмена в одном и том
// же порядке. Advisory-lock не меняет строку, но сериализует два обмена, которые
// используют хотя бы одно общее объявление. Коллизия хэша безопасна: она только
// заставит два независимых запроса ненадолго выполняться последовательно.
func (q *Queries) LockExchangeDecisionItems(ctx context.Context, exchangeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockExchangeDecisionItems, exchangeID)
	return err
}

const lockExchangeItems = `-- name: LockExchangeItems :many
SELECT item.id, item.owner_id, item.status
FROM items AS item
JOIN chain_participants AS participant
  ON participant.gives_item_id = item.id
WHERE participant.chain_id = $1
ORDER BY item.id
FOR UPDATE OF item
`

type LockExchangeItemsRow struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
	Status  ItemStatus
}

// Вещи блокируются в одинаковом порядке UUID. Это защищает конкурирующие обмены
// от двойного резервирования и уменьшает риск взаимной блокировки транзакций.
func (q *Queries) LockExchangeItems(ctx context.Context, exchangeID pgtype.UUID) ([]LockExchangeItemsRow, error) {
	rows, err := q.db.Query(ctx, lockExchangeItems, exchangeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockExchangeItemsRow
	for rows.Next() {
		var i LockExchangeItemsRow
		if err := rows.Scan(&i.ID, &i.OwnerID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExchangeParticipant = `-- name: LockExchangeParticipant :one
SELECT status, completion_confirmed_at
FROM chain_participants
WHERE chain_id = $1
  AND user_id = $2
FOR UPDATE
`

type LockExchangeParticipantParams struct {
	ExchangeID pgtype.UUID
	UserID     pgtype.UUID
}

type LockExchangeParticipantRow struct {
	Status                ParticipantStatus
	CompletionConfirmedAt pgtype.Timestamptz
}

func (q *Queries) LockExchangeParticipant(ctx context.Context, arg LockExchangeParticipantParams) (LockExchangeParticipantRow, error) {
	row := q.db.QueryRow(ctx, lockExchangeParticipant, arg.ExchangeID, arg.UserID)
	var i LockExchangeParticipantRow
	err := row.Scan(&i.Status, &i.CompletionConfirmedAt)
	return i, err
}

const markExchangeDelivered = `-- name: MarkExchangeDelivered :execrows
UPDATE chains
SET status = 'delivered'
WHERE chains.id = $1
  AND chains.status = 'delivering'
  AND NOT EXISTS (
      SELECT 1
      FROM chain_participants AS participant
      JOIN items AS item ON item.id = participant.gives_item_id
      WHERE participant.chain_id = $1
        AND item.pickup_point_id IS NULL
  )
`

// Администратор завершает физическую доставку всей цепочки одной командой. Проверка
// пунктов продублирована намеренно: status = 'delivering' уже означает, что все вещи
// сданы, но это условие не даст некорректным старым данным перейти к получению.
func (q *Queries) MarkExchangeDelivered(ctx context.Context, exchangeID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markExchangeDelivered, exchangeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const promoteExchangeToDelivering = `-- name: PromoteExchangeToDelivering :execrows
UPDATE chains
SET status = 'delivering'
WHERE chains.id = $1
  AND chains.status = 'confirmed'
  AND NOT EXISTS (
      SELECT 1
      FROM chain_participants AS participant
      JOIN items AS item ON item.id = participant.gives_item_id
      WHERE participant.chain_id = $1
        AND item.pickup_point_id IS NULL
  )
`

// Переход в доставку — одно выражение, а не «прочитать вещи в Go и потом записать статус»:
// иначе проверка гонялась бы с параллельной сдачей вещи соседом. Условие status = 'confirmed'
// делает вызов идемпотентным, поэтому его безопасно дёргать и из сдачи вещи, и из последнего
// подтверждения участия. closed_at не трогаем: обмен не закрыт, он едет.
func (q *Queries) PromoteExchangeToDelivering(ctx context.Context, exchangeID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, promoteExchangeToDelivering, exchangeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordBrokenExchangeComposition = `-- name: RecordBrokenExchangeComposition :exec
INSERT INTO broken_exchange_compositions (composition_key, source_chain_id)
SELECT composition_key, id
FROM chains
WHERE id = $1
  AND status = 'confirmed'
ON CONFLICT DO NOTHING
`

// Точный состав блокируется только при срыве confirmed. Повторная запись безопасна,
// но в нормальном потоке тот же composition_key уже не сможет создать новый обмен.
func (q *Queries) RecordBrokenExchangeComposition(ctx context.Context, exchangeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordBrokenExchangeComposition, exchangeID)
	return err
}

const recordItemRefusal = `-- name: RecordItemRefusal :exec
INSERT INTO item_refusals (user_id, item_id)
SELECT participant.user_id, participant.receives_item_id
FROM chain_participants AS participant
WHERE participant.chain_id = $1
  AND participant.user_id = $2
ON CONFLICT DO NOTHING
`

type RecordItemRefusalParams struct {
	ExchangeID pgtype.UUID
	UserID     pgtype.UUID
}

// Отказ от предложения — «не хочу эту вещь», поэтому запоминается вырезанным ребром:
// вещь берётся из самой цепочки, отдельного чтения в Go не нужно. Повторный отказ от
// той же вещи в другом обмене — нормальный случай, а не ошибка.
func (q *Queries) RecordItemRefusal(ctx context.Context, arg RecordItemRefusalParams) error {
	_, err := q.db.Exec(ctx, recordItemRefusal, arg.ExchangeID, arg.UserID)
	return err
}

const releaseExchangeItems = `-- name: ReleaseExchangeItems :execrows
UPDATE items
SET status = 'available'
WHERE id IN (
    SELECT gives_item_id
    FROM chain_participants
    WHERE chain_id = $1
)
  AND status = 'reserved'
`

// Подтверждённый обмен уже зарезервировал вещи. При его отмене освобождаем только
// вещи этого обмена и только из reserved: чужое параллельное изменение не затирается.
func (q *Queries) ReleaseExchangeItems(ctx context.Context, exchangeID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseExchangeItems, exchangeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveExchangeItems = `-- name: ReserveExchangeItems :execrows
UPDATE items
SET status = 'reserved'
WHERE id IN (
    SELECT gives_item_id
    FROM chain_participants
    WHERE chain_id = $1
)
  AND status = 'available'
`

func (q *Queries) ReserveExchangeItems(ctx context.Context, exchangeID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, reserveExchangeItems, exchangeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
