// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_save.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExchange = `-- name: CreateExchange :one
INSERT INTO chains (signature, composition_key)
SELECT $1, $2
WHERE NOT EXISTS (
    SELECT 1
    FROM broken_exchange_compositions AS broken
    WHERE broken.composition_key = $2
)
ON CONFLICT DO NOTHING
RETURNING id
`

type CreateExchangeParams struct {
	Signature      string
	CompositionKey string
}

// Направленная подпись сохраняется для диагностики, а composition_key защищает
// фактический набор объявлений. Безымянный ON CONFLICT учитывает оба частичных
// уникальных индекса и атомарно гасит гонку параллельных DFS.
func (q *Queries) CreateExchange(ctx context.Context, arg CreateExchangeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createExchange, arg.Signature, arg.CompositionKey)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createExchangeParticipant = `-- name: CreateExchangeParticipant :exec
INSERT INTO chain_participants (
    chain_id,
    user_id,
    gives_item_id,
    receives_item_id,
    position
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateExchangeParticipantParams struct {
	ChainID        pgtype.UUID
	UserID         pgtype.UUID
	GivesItemID    pgtype.UUID
	ReceivesItemID pgtype.UUID
	Position       int32
}

func (q *Queries) CreateExchangeParticipant(ctx context.Context, arg CreateExchangeParticipantParams) error {
	_, err := q.db.Exec(ctx, createExchangeParticipant,
		arg.ChainID,
		arg.UserID,
		arg.GivesItemID,
		arg.ReceivesItemID,
		arg.Position,
	)
	return err
}

const lockExchangeComposition = `-- name: LockExchangeComposition :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 1))
`

// Блокировка и INSERT намеренно разделены. В READ COMMITTED запрос, ожидавший
// advisory lock, сохранил бы старый snapshot и мог не увидеть только что
// зафиксированный запрет. Следующий запрос получает свежий snapshot.
func (q *Queries) LockExchangeComposition(ctx context.Context, compositionKey string) error {
	_, err := q.db.Exec(ctx, lockExchangeComposition, compositionKey)
	return err
}
