// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_completion.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearExchangeItemsPickupPoint = `-- name: ClearExchangeItemsPickupPoint :exec
UPDATE items
SET pickup_point_id = NULL
WHERE id IN (
    SELECT gives_item_id
    FROM chain_participants
    WHERE chain_id = $1
)
`

// Вещи разъехались по новым владельцам, поэтому пункт хранения обнуляется вместе с
// переходом в traded: иначе завершённая вещь навсегда осталась бы «лежащей в ПВЗ» и
// держала бы его от удаления внешним ключом.
func (q *Queries) ClearExchangeItemsPickupPoint(ctx context.Context, exchangeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearExchangeItemsPickupPoint, exchangeID)
	return err
}

const completeExchange = `-- name: CompleteExchange :exec
UPDATE chains
SET status = 'completed',
    closed_at = now()
WHERE id = $1
`

func (q *Queries) CompleteExchange(ctx context.Context, exchangeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeExchange, exchangeID)
	return err
}

const confirmExchangeParticipantCompletion = `-- name: ConfirmExchangeParticipantCompletion :exec
UPDATE chain_participants
SET completion_confirmed_at = now()
WHERE chain_id = $1
  AND user_id = $2
`

type ConfirmExchangeParticipantCompletionParams struct {
	ExchangeID pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) ConfirmExchangeParticipantCompletion(ctx context.Context, arg ConfirmExchangeParticipantCompletionParams) error {
	_, err := q.db.Exec(ctx, confirmExchangeParticipantCompletion, arg.ExchangeID, arg.UserID)
	return err
}

const countIncompleteExchangeParticipants = `-- name: CountIncompleteExchangeParticipants :one
SELECT count(*)
FROM chain_participants
WHERE chain_id = $1
  AND completion_confirmed_at IS NULL
`

func (q *Queries) CountIncompleteExchangeParticipants(ctx context.Context, exchangeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIncompleteExchangeParticipants, exchangeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementExchangeParticipantsDealsCompleted = `-- name: IncrementExchangeParticipantsDealsCompleted :execrows
UPDATE users
SET deals_completed = deals_completed + 1
WHERE id IN (
    SELECT user_id
    FROM chain_participants
    WHERE chain_id = $1
)
`

func (q *Queries) IncrementExchangeParticipantsDealsCompleted(ctx context.Context, exchangeID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incrementExchangeParticipantsDealsCompleted, exchangeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockExchangeCompletionParticipant = `-- name: LockExchangeCompletionParticipant :one
SELECT status, completion_confirmed_at
FROM chain_participants
WHERE chain_id = $1
  AND user_id = $2
FOR UPDATE
`

type LockExchangeCompletionParticipantParams struct {
	ExchangeID pgtype.UUID
	UserID     pgtype.UUID
}

type LockExchangeCompletionParticipantRow struct {
	Status                ParticipantStatus
	CompletionConfirmedAt pgtype.Timestamptz
}

func (q *Queries) LockExchangeCompletionParticipant(ctx context.Context, arg LockExchangeCompletionParticipantParams) (LockExchangeCompletionParticipantRow, error) {
	row := q.db.QueryRow(ctx, lockExchangeCompletionParticipant, arg.ExchangeID, arg.UserID)
	var i LockExchangeCompletionParticipantRow
	err := row.Scan(&i.Status, &i.CompletionConfirmedAt)
	return i, err
}

const markExchangeItemsTraded = `-- name: MarkExchangeItemsTraded :execrows
UPDATE items
SET status = 'traded'
WHERE id IN (
    SELECT gives_item_id
    FROM chain_participants
    WHERE chain_id = $1
)
  AND status = 'reserved'
`

func (q *Queries) MarkExchangeItemsTraded(ctx context.Context, exchangeID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markExchangeItemsTraded, exchangeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
