// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findExchangeNeighbors = `-- name: FindExchangeNeighbors :many
SELECT
    candidate.id,
    candidate.owner_id
FROM items AS current_item
JOIN item_wants AS wanted
    ON wanted.item_id = current_item.id
JOIN items AS candidate
    ON candidate.category_id = wanted.category_id
WHERE current_item.id = $1
  AND current_item.status = 'available'
  AND candidate.status = 'available'
  AND candidate.id <> current_item.id
  AND candidate.owner_id <> current_item.owner_id
  AND NOT EXISTS (
      SELECT 1
      FROM item_refusals AS refusal
      WHERE refusal.user_id = current_item.owner_id
        AND refusal.item_id = candidate.id
  )
ORDER BY candidate.created_at, candidate.id
`

type FindExchangeNeighborsRow struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

// Рёбра графа не храним: для объявления A соседями считаются доступные объявления B,
// категория которых входит в список желаемых категорий A и от которых владелец A не
// отказывался.
// Стабильный порядок нужен, чтобы DFS при одинаковых данных находил одинаковый обмен.
func (q *Queries) FindExchangeNeighbors(ctx context.Context, itemID pgtype.UUID) ([]FindExchangeNeighborsRow, error) {
	rows, err := q.db.Query(ctx, findExchangeNeighbors, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindExchangeNeighborsRow
	for rows.Next() {
		var i FindExchangeNeighborsRow
		if err := rows.Scan(&i.ID, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserBlockConflict = `-- name: HasUserBlockConflict :one
SELECT EXISTS (
    SELECT 1
    FROM user_blocks AS block
    WHERE (
        block.blocker_id = $1
        AND block.blocked_id = ANY($2::uuid[])
    ) OR (
        block.blocked_id = $1
        AND block.blocker_id = ANY($2::uuid[])
    )
)
`

type HasUserBlockConflictParams struct {
	CandidateUserID pgtype.UUID
	PathUserIds     []pgtype.UUID
}

// Кандидат несовместим с текущим путём, если он заблокировал хотя бы одного
// уже выбранного владельца или кто-то из них заблокировал кандидата.
func (q *Queries) HasUserBlockConflict(ctx context.Context, arg HasUserBlockConflictParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserBlockConflict, arg.CandidateUserID, arg.PathUserIds)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listExchangeSearchUserStats = `-- name: ListExchangeSearchUserStats :many
SELECT
    id,
    deals_completed,
    deals_broken,
    COALESCE(rating::double precision, 3.0)::double precision AS rating
FROM users
WHERE id = ANY($1::uuid[])
`

type ListExchangeSearchUserStatsRow struct {
	ID             pgtype.UUID
	DealsCompleted int32
	DealsBroken    int32
	Rating         float64
}

// Статистика читается одним запросом для всех владельцев найденных циклов. Пользователь
// без рейтинга получает нейтральные 3.0, чтобы новый аккаунт не оказался автоматически
// хуже аккаунта с одной оценкой.
func (q *Queries) ListExchangeSearchUserStats(ctx context.Context, userIds []pgtype.UUID) ([]ListExchangeSearchUserStatsRow, error) {
	rows, err := q.db.Query(ctx, listExchangeSearchUserStats, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExchangeSearchUserStatsRow
	for rows.Next() {
		var i ListExchangeSearchUserStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.DealsCompleted,
			&i.DealsBroken,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
