// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_save.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExchange = `-- name: CreateExchange :one
INSERT INTO chains (signature)
VALUES ($1)
ON CONFLICT (signature) DO NOTHING
RETURNING id
`

func (q *Queries) CreateExchange(ctx context.Context, signature string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createExchange, signature)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createExchangeParticipant = `-- name: CreateExchangeParticipant :exec
INSERT INTO chain_participants (
    chain_id,
    user_id,
    gives_item_id,
    receives_item_id,
    position
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateExchangeParticipantParams struct {
	ChainID        pgtype.UUID
	UserID         pgtype.UUID
	GivesItemID    pgtype.UUID
	ReceivesItemID pgtype.UUID
	Position       int32
}

func (q *Queries) CreateExchangeParticipant(ctx context.Context, arg CreateExchangeParticipantParams) error {
	_, err := q.db.Exec(ctx, createExchangeParticipant,
		arg.ChainID,
		arg.UserID,
		arg.GivesItemID,
		arg.ReceivesItemID,
		arg.Position,
	)
	return err
}
