// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_decision.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptExchangeParticipant = `-- name: AcceptExchangeParticipant :exec
UPDATE chain_participants
SET status = 'accepted',
    decided_at = now()
WHERE chain_id = $1
  AND user_id = $2
`

type AcceptExchangeParticipantParams struct {
	ExchangeID pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) AcceptExchangeParticipant(ctx context.Context, arg AcceptExchangeParticipantParams) error {
	_, err := q.db.Exec(ctx, acceptExchangeParticipant, arg.ExchangeID, arg.UserID)
	return err
}

const cancelExchange = `-- name: CancelExchange :exec
UPDATE chains
SET status = 'cancelled',
    closed_at = now()
WHERE id = $1
`

func (q *Queries) CancelExchange(ctx context.Context, exchangeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelExchange, exchangeID)
	return err
}

const confirmExchange = `-- name: ConfirmExchange :exec
UPDATE chains
SET status = 'confirmed'
WHERE id = $1
`

func (q *Queries) ConfirmExchange(ctx context.Context, exchangeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, confirmExchange, exchangeID)
	return err
}

const countPendingExchangeParticipants = `-- name: CountPendingExchangeParticipants :one
SELECT count(*)
FROM chain_participants
WHERE chain_id = $1
  AND status = 'pending'
`

func (q *Queries) CountPendingExchangeParticipants(ctx context.Context, exchangeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingExchangeParticipants, exchangeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const declineExchangeParticipant = `-- name: DeclineExchangeParticipant :exec
UPDATE chain_participants
SET status = 'declined',
    decided_at = now()
WHERE chain_id = $1
  AND user_id = $2
`

type DeclineExchangeParticipantParams struct {
	ExchangeID pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) DeclineExchangeParticipant(ctx context.Context, arg DeclineExchangeParticipantParams) error {
	_, err := q.db.Exec(ctx, declineExchangeParticipant, arg.ExchangeID, arg.UserID)
	return err
}

const lockExchange = `-- name: LockExchange :one
SELECT status
FROM chains
WHERE id = $1
FOR UPDATE
`

// Строка обмена блокируется первой. Поэтому два одновременных решения по одному
// обмену выполняются последовательно и не могут потерять обновления друг друга.
func (q *Queries) LockExchange(ctx context.Context, exchangeID pgtype.UUID) (ChainStatus, error) {
	row := q.db.QueryRow(ctx, lockExchange, exchangeID)
	var status ChainStatus
	err := row.Scan(&status)
	return status, err
}

const lockExchangeItems = `-- name: LockExchangeItems :many
SELECT item.id, item.status
FROM items AS item
JOIN chain_participants AS participant
  ON participant.gives_item_id = item.id
WHERE participant.chain_id = $1
ORDER BY item.id
FOR UPDATE OF item
`

type LockExchangeItemsRow struct {
	ID     pgtype.UUID
	Status ItemStatus
}

// Вещи блокируются в одинаковом порядке UUID. Это защищает конкурирующие обмены
// от двойного резервирования и уменьшает риск взаимной блокировки транзакций.
func (q *Queries) LockExchangeItems(ctx context.Context, exchangeID pgtype.UUID) ([]LockExchangeItemsRow, error) {
	rows, err := q.db.Query(ctx, lockExchangeItems, exchangeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockExchangeItemsRow
	for rows.Next() {
		var i LockExchangeItemsRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExchangeParticipant = `-- name: LockExchangeParticipant :one
SELECT status
FROM chain_participants
WHERE chain_id = $1
  AND user_id = $2
FOR UPDATE
`

type LockExchangeParticipantParams struct {
	ExchangeID pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) LockExchangeParticipant(ctx context.Context, arg LockExchangeParticipantParams) (ParticipantStatus, error) {
	row := q.db.QueryRow(ctx, lockExchangeParticipant, arg.ExchangeID, arg.UserID)
	var status ParticipantStatus
	err := row.Scan(&status)
	return status, err
}

const reserveExchangeItems = `-- name: ReserveExchangeItems :execrows
UPDATE items
SET status = 'reserved'
WHERE id IN (
    SELECT gives_item_id
    FROM chain_participants
    WHERE chain_id = $1
)
  AND status = 'available'
`

func (q *Queries) ReserveExchangeItems(ctx context.Context, exchangeID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, reserveExchangeItems, exchangeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
