// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findExchangeNeighbors = `-- name: FindExchangeNeighbors :many
SELECT
    candidate.id,
    candidate.owner_id
FROM items AS current_item
JOIN item_wants AS wanted
    ON wanted.item_id = current_item.id
JOIN items AS candidate
    ON candidate.category_id = wanted.category_id
WHERE current_item.id = $1
  AND current_item.status = 'available'
  AND candidate.status = 'available'
  AND candidate.id <> current_item.id
  AND candidate.owner_id <> current_item.owner_id
ORDER BY candidate.created_at, candidate.id
`

type FindExchangeNeighborsRow struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

// Рёбра графа не храним: для объявления A соседями считаются доступные объявления B,
// категория которых входит в список желаемых категорий A.
// Стабильный порядок нужен, чтобы DFS при одинаковых данных находил одинаковый обмен.
func (q *Queries) FindExchangeNeighbors(ctx context.Context, itemID pgtype.UUID) ([]FindExchangeNeighborsRow, error) {
	rows, err := q.db.Query(ctx, findExchangeNeighbors, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindExchangeNeighborsRow
	for rows.Next() {
		var i FindExchangeNeighborsRow
		if err := rows.Scan(&i.ID, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
