// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_read.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExchangeByID = `-- name: GetExchangeByID :many
SELECT
    exchange.id          AS exchange_id,
    exchange.status      AS exchange_status,
    exchange.created_at  AS exchange_created_at,
    exchange.updated_at  AS exchange_updated_at,
    exchange.closed_at   AS exchange_closed_at,
    participant.user_id,
    participant.position,
    participant.status   AS participant_status,
    participant.decided_at,
    participant.completion_confirmed_at,
    exchange_user.nickname,
    exchange_user.photo_url AS user_photo_url,
    gives_item.id          AS gives_item_id,
    gives_item.title       AS gives_item_title,
    gives_item.description AS gives_item_description,
    gives_item.status      AS gives_item_status,
    gives_category.slug    AS gives_category_slug,
    gives_category.name    AS gives_category_name,
    receives_item.id          AS receives_item_id,
    receives_item.title       AS receives_item_title,
    receives_item.description AS receives_item_description,
    receives_item.status      AS receives_item_status,
    receives_category.slug    AS receives_category_slug,
    receives_category.name    AS receives_category_name
FROM chains AS exchange
JOIN chain_participants AS participant
    ON participant.chain_id = exchange.id
JOIN users AS exchange_user
    ON exchange_user.id = participant.user_id
JOIN items AS gives_item
    ON gives_item.id = participant.gives_item_id
JOIN categories AS gives_category
    ON gives_category.id = gives_item.category_id
JOIN items AS receives_item
    ON receives_item.id = participant.receives_item_id
JOIN categories AS receives_category
    ON receives_category.id = receives_item.category_id
WHERE exchange.id = $1
ORDER BY participant.position
`

type GetExchangeByIDRow struct {
	ExchangeID              pgtype.UUID
	ExchangeStatus          ChainStatus
	ExchangeCreatedAt       pgtype.Timestamptz
	ExchangeUpdatedAt       pgtype.Timestamptz
	ExchangeClosedAt        pgtype.Timestamptz
	UserID                  pgtype.UUID
	Position                int32
	ParticipantStatus       ParticipantStatus
	DecidedAt               pgtype.Timestamptz
	CompletionConfirmedAt   pgtype.Timestamptz
	Nickname                string
	UserPhotoUrl            pgtype.Text
	GivesItemID             pgtype.UUID
	GivesItemTitle          string
	GivesItemDescription    string
	GivesItemStatus         ItemStatus
	GivesCategorySlug       string
	GivesCategoryName       string
	ReceivesItemID          pgtype.UUID
	ReceivesItemTitle       string
	ReceivesItemDescription string
	ReceivesItemStatus      ItemStatus
	ReceivesCategorySlug    string
	ReceivesCategoryName    string
}

func (q *Queries) GetExchangeByID(ctx context.Context, exchangeID pgtype.UUID) ([]GetExchangeByIDRow, error) {
	rows, err := q.db.Query(ctx, getExchangeByID, exchangeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExchangeByIDRow
	for rows.Next() {
		var i GetExchangeByIDRow
		if err := rows.Scan(
			&i.ExchangeID,
			&i.ExchangeStatus,
			&i.ExchangeCreatedAt,
			&i.ExchangeUpdatedAt,
			&i.ExchangeClosedAt,
			&i.UserID,
			&i.Position,
			&i.ParticipantStatus,
			&i.DecidedAt,
			&i.CompletionConfirmedAt,
			&i.Nickname,
			&i.UserPhotoUrl,
			&i.GivesItemID,
			&i.GivesItemTitle,
			&i.GivesItemDescription,
			&i.GivesItemStatus,
			&i.GivesCategorySlug,
			&i.GivesCategoryName,
			&i.ReceivesItemID,
			&i.ReceivesItemTitle,
			&i.ReceivesItemDescription,
			&i.ReceivesItemStatus,
			&i.ReceivesCategorySlug,
			&i.ReceivesCategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExchangesByUser = `-- name: ListExchangesByUser :many
SELECT
    exchange.id          AS exchange_id,
    exchange.status      AS exchange_status,
    exchange.created_at  AS exchange_created_at,
    exchange.updated_at  AS exchange_updated_at,
    exchange.closed_at   AS exchange_closed_at,
    participant.user_id,
    participant.position,
    participant.status   AS participant_status,
    participant.decided_at,
    participant.completion_confirmed_at,
    exchange_user.nickname,
    exchange_user.photo_url AS user_photo_url,
    gives_item.id          AS gives_item_id,
    gives_item.title       AS gives_item_title,
    gives_item.description AS gives_item_description,
    gives_item.status      AS gives_item_status,
    gives_category.slug    AS gives_category_slug,
    gives_category.name    AS gives_category_name,
    receives_item.id          AS receives_item_id,
    receives_item.title       AS receives_item_title,
    receives_item.description AS receives_item_description,
    receives_item.status      AS receives_item_status,
    receives_category.slug    AS receives_category_slug,
    receives_category.name    AS receives_category_name
FROM chains AS exchange
JOIN chain_participants AS participant
    ON participant.chain_id = exchange.id
JOIN users AS exchange_user
    ON exchange_user.id = participant.user_id
JOIN items AS gives_item
    ON gives_item.id = participant.gives_item_id
JOIN categories AS gives_category
    ON gives_category.id = gives_item.category_id
JOIN items AS receives_item
    ON receives_item.id = participant.receives_item_id
JOIN categories AS receives_category
    ON receives_category.id = receives_item.category_id
WHERE EXISTS (
    SELECT 1
    FROM chain_participants AS current_participant
    WHERE current_participant.chain_id = exchange.id
      AND current_participant.user_id = $1
)
ORDER BY exchange.created_at DESC, exchange.id, participant.position
`

type ListExchangesByUserRow struct {
	ExchangeID              pgtype.UUID
	ExchangeStatus          ChainStatus
	ExchangeCreatedAt       pgtype.Timestamptz
	ExchangeUpdatedAt       pgtype.Timestamptz
	ExchangeClosedAt        pgtype.Timestamptz
	UserID                  pgtype.UUID
	Position                int32
	ParticipantStatus       ParticipantStatus
	DecidedAt               pgtype.Timestamptz
	CompletionConfirmedAt   pgtype.Timestamptz
	Nickname                string
	UserPhotoUrl            pgtype.Text
	GivesItemID             pgtype.UUID
	GivesItemTitle          string
	GivesItemDescription    string
	GivesItemStatus         ItemStatus
	GivesCategorySlug       string
	GivesCategoryName       string
	ReceivesItemID          pgtype.UUID
	ReceivesItemTitle       string
	ReceivesItemDescription string
	ReceivesItemStatus      ItemStatus
	ReceivesCategorySlug    string
	ReceivesCategoryName    string
}

// Все участники нужны frontend, поэтому пользователя фильтруем через EXISTS,
// а не через основной JOIN: иначе в ответе осталась бы только его строка.
func (q *Queries) ListExchangesByUser(ctx context.Context, userID pgtype.UUID) ([]ListExchangesByUserRow, error) {
	rows, err := q.db.Query(ctx, listExchangesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExchangesByUserRow
	for rows.Next() {
		var i ListExchangesByUserRow
		if err := rows.Scan(
			&i.ExchangeID,
			&i.ExchangeStatus,
			&i.ExchangeCreatedAt,
			&i.ExchangeUpdatedAt,
			&i.ExchangeClosedAt,
			&i.UserID,
			&i.Position,
			&i.ParticipantStatus,
			&i.DecidedAt,
			&i.CompletionConfirmedAt,
			&i.Nickname,
			&i.UserPhotoUrl,
			&i.GivesItemID,
			&i.GivesItemTitle,
			&i.GivesItemDescription,
			&i.GivesItemStatus,
			&i.GivesCategorySlug,
			&i.GivesCategoryName,
			&i.ReceivesItemID,
			&i.ReceivesItemTitle,
			&i.ReceivesItemDescription,
			&i.ReceivesItemStatus,
			&i.ReceivesCategorySlug,
			&i.ReceivesCategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
