// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteItem = `-- name: DeleteItem :execrows
DELETE FROM items WHERE id = $1
`

// :execrows — ноль удалённых строк отличает «не было такой вещи» (404) от успеха.
func (q *Queries) DeleteItem(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteItemWants = `-- name: DeleteItemWants :exec
DELETE FROM item_wants WHERE item_id = $1
`

func (q *Queries) DeleteItemWants(ctx context.Context, itemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemWants, itemID)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT
    i.id, i.owner_id, i.category_id, i.title, i.description, i.status, i.created_at, i.updated_at, i.photo_urls, i.pickup_point_id, i.max_chain_length, i.min_participant_rating, i.prefer_reliable_participants,
    c.slug AS category,
    COALESCE(
        (SELECT array_agg(want_category.slug ORDER BY want_category.slug)
         FROM item_wants w
         JOIN categories want_category ON want_category.id = w.category_id
         WHERE w.item_id = i.id),
        '{}'
    )::text[] AS wants,
    pickup_point.name    AS pickup_point_name,
    pickup_point.address AS pickup_point_address
FROM items i
JOIN categories c ON c.id = i.category_id
LEFT JOIN pickup_points AS pickup_point ON pickup_point.id = i.pickup_point_id
WHERE i.id = $1
`

type GetItemByIDRow struct {
	ID                         pgtype.UUID
	OwnerID                    pgtype.UUID
	CategoryID                 int16
	Title                      string
	Description                string
	Status                     ItemStatus
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	PhotoUrls                  []string
	PickupPointID              pgtype.UUID
	MaxChainLength             int32
	MinParticipantRating       float64
	PreferReliableParticipants bool
	Category                   string
	Wants                      []string
	PickupPointName            pgtype.Text
	PickupPointAddress         pgtype.Text
}

// Пункт выдачи джойнится LEFT: у вещи дома его нет, и INNER молча выбросил бы её из
// карточки. Сам pickup_point_id приезжает в i.*, здесь добираются только имя и адрес.
func (q *Queries) GetItemByID(ctx context.Context, id pgtype.UUID) (GetItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i GetItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhotoUrls,
		&i.PickupPointID,
		&i.MaxChainLength,
		&i.MinParticipantRating,
		&i.PreferReliableParticipants,
		&i.Category,
		&i.Wants,
		&i.PickupPointName,
		&i.PickupPointAddress,
	)
	return i, err
}

const insertItem = `-- name: InsertItem :one

INSERT INTO items (
    owner_id,
    category_id,
    title,
    description,
    photo_urls,
    max_chain_length,
    min_participant_rating,
    prefer_reliable_participants
)
VALUES (
    $1,
    (SELECT id FROM categories WHERE slug = $2),
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id
`

type InsertItemParams struct {
	OwnerID                    pgtype.UUID
	Category                   string
	Title                      string
	Description                string
	PhotoUrls                  []string
	MaxChainLength             int32
	MinParticipantRating       float64
	PreferReliableParticipants bool
}

// Категории приходят из API слагами, а не числовыми id: slug — стабильный публичный ключ.
// Разыменование живёт прямо в запросе, и неизвестный слаг превращается в NULL, который
// ловит NOT NULL на колонке. Так «такой категории нет» — ошибка БД, а не тихая подстановка.
func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertItem,
		arg.OwnerID,
		arg.Category,
		arg.Title,
		arg.Description,
		arg.PhotoUrls,
		arg.MaxChainLength,
		arg.MinParticipantRating,
		arg.PreferReliableParticipants,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertItemWants = `-- name: InsertItemWants :exec
INSERT INTO item_wants (item_id, category_id)
SELECT $1::uuid, c.id
FROM unnest($2::text[]) AS want(slug)
LEFT JOIN categories c ON c.slug = want.slug
`

type InsertItemWantsParams struct {
	ItemID pgtype.UUID
	Wants  []string
}

// LEFT JOIN, а не INNER: неизвестный слаг даёт строку с category_id = NULL и валит вставку.
// INNER молча выбросил бы её, и пользователь получил бы 201 с потерянным желанием.
func (q *Queries) InsertItemWants(ctx context.Context, arg InsertItemWantsParams) error {
	_, err := q.db.Exec(ctx, insertItemWants, arg.ItemID, arg.Wants)
	return err
}

const itemHasOpenExchange = `-- name: ItemHasOpenExchange :one
SELECT EXISTS (
    SELECT 1
    FROM chain_participants AS participant
    JOIN chains AS exchange ON exchange.id = participant.chain_id
    WHERE (participant.gives_item_id = $1
           OR participant.receives_item_id = $1)
      AND exchange.status IN ('proposed', 'confirmed', 'delivering', 'delivered')
)
`

func (q *Queries) ItemHasOpenExchange(ctx context.Context, itemID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, itemHasOpenExchange, itemID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listItemsByOwner = `-- name: ListItemsByOwner :many
SELECT
    i.id, i.owner_id, i.category_id, i.title, i.description, i.status, i.created_at, i.updated_at, i.photo_urls, i.pickup_point_id, i.max_chain_length, i.min_participant_rating, i.prefer_reliable_participants,
    c.slug AS category,
    COALESCE(
        (SELECT array_agg(want_category.slug ORDER BY want_category.slug)
         FROM item_wants w
         JOIN categories want_category ON want_category.id = w.category_id
         WHERE w.item_id = i.id),
        '{}'
    )::text[] AS wants,
    pickup_point.name    AS pickup_point_name,
    pickup_point.address AS pickup_point_address
FROM items i
JOIN categories c ON c.id = i.category_id
LEFT JOIN pickup_points AS pickup_point ON pickup_point.id = i.pickup_point_id
WHERE i.owner_id = $1
ORDER BY i.created_at DESC, i.id
`

type ListItemsByOwnerRow struct {
	ID                         pgtype.UUID
	OwnerID                    pgtype.UUID
	CategoryID                 int16
	Title                      string
	Description                string
	Status                     ItemStatus
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	PhotoUrls                  []string
	PickupPointID              pgtype.UUID
	MaxChainLength             int32
	MinParticipantRating       float64
	PreferReliableParticipants bool
	Category                   string
	Wants                      []string
	PickupPointName            pgtype.Text
	PickupPointAddress         pgtype.Text
}

// Колонки те же и в том же порядке, что у GetItemByID: sqlc генерит идентичную
// структуру, и репозиторию хватает одного маппера на оба запроса.
func (q *Queries) ListItemsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]ListItemsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listItemsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsByOwnerRow
	for rows.Next() {
		var i ListItemsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PhotoUrls,
			&i.PickupPointID,
			&i.MaxChainLength,
			&i.MinParticipantRating,
			&i.PreferReliableParticipants,
			&i.Category,
			&i.Wants,
			&i.PickupPointName,
			&i.PickupPointAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :exec
UPDATE items SET
    title       = COALESCE($1, title),
    description = COALESCE($2, description),
    photo_urls  = COALESCE($3::text[], photo_urls),
    max_chain_length = COALESCE($4, max_chain_length),
    min_participant_rating = COALESCE($5, min_participant_rating),
    prefer_reliable_participants = COALESCE(
        $6,
        prefer_reliable_participants
    ),
    category_id = CASE
        WHEN $7::text IS NULL THEN items.category_id
        ELSE (SELECT c.id FROM categories c WHERE c.slug = $7)
    END
WHERE items.id = $8
`

type UpdateItemParams struct {
	Title                      pgtype.Text
	Description                pgtype.Text
	PhotoUrls                  []string
	MaxChainLength             pgtype.Int4
	MinParticipantRating       pgtype.Float8
	PreferReliableParticipants pgtype.Bool
	Category                   pgtype.Text
	ID                         pgtype.UUID
}

// NULL в аргументе означает «не менять поле» — тот же приём, что в UpdateUserProfile.
// Категория идёт через CASE, а не COALESCE: COALESCE не отличил бы «не передана»
// от «передана несуществующая» и во втором случае молча оставил бы старую.
func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.Exec(ctx, updateItem,
		arg.Title,
		arg.Description,
		arg.PhotoUrls,
		arg.MaxChainLength,
		arg.MinParticipantRating,
		arg.PreferReliableParticipants,
		arg.Category,
		arg.ID,
	)
	return err
}
