// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteItem = `-- name: DeleteItem :execrows
DELETE FROM items WHERE id = $1
`

// :execrows — ноль удалённых строк отличает «не было такой вещи» (404) от успеха.
func (q *Queries) DeleteItem(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteItemWants = `-- name: DeleteItemWants :exec
DELETE FROM item_wants WHERE item_id = $1
`

func (q *Queries) DeleteItemWants(ctx context.Context, itemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemWants, itemID)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT
    i.id, i.owner_id, i.category_id, i.title, i.description, i.status, i.created_at, i.updated_at, i.photo_urls,
    c.slug AS category,
    COALESCE(
        (SELECT array_agg(want_category.slug ORDER BY want_category.slug)
         FROM item_wants w
         JOIN categories want_category ON want_category.id = w.category_id
         WHERE w.item_id = i.id),
        '{}'
    )::text[] AS wants
FROM items i
JOIN categories c ON c.id = i.category_id
WHERE i.id = $1
`

type GetItemByIDRow struct {
	ID          pgtype.UUID
	OwnerID     pgtype.UUID
	CategoryID  int16
	Title       string
	Description string
	Status      ItemStatus
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	PhotoUrls   []string
	Category    string
	Wants       []string
}

func (q *Queries) GetItemByID(ctx context.Context, id pgtype.UUID) (GetItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i GetItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhotoUrls,
		&i.Category,
		&i.Wants,
	)
	return i, err
}

const insertItem = `-- name: InsertItem :one

INSERT INTO items (owner_id, category_id, title, description, photo_urls)
VALUES (
    $1,
    (SELECT id FROM categories WHERE slug = $2),
    $3,
    $4,
    $5
)
RETURNING id
`

type InsertItemParams struct {
	OwnerID     pgtype.UUID
	Category    string
	Title       string
	Description string
	PhotoUrls   []string
}

// Категории приходят из API слагами, а не числовыми id: slug — стабильный публичный ключ.
// Разыменование живёт прямо в запросе, и неизвестный слаг превращается в NULL, который
// ловит NOT NULL на колонке. Так «такой категории нет» — ошибка БД, а не тихая подстановка.
func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertItem,
		arg.OwnerID,
		arg.Category,
		arg.Title,
		arg.Description,
		arg.PhotoUrls,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertItemWants = `-- name: InsertItemWants :exec
INSERT INTO item_wants (item_id, category_id)
SELECT $1::uuid, c.id
FROM unnest($2::text[]) AS want(slug)
LEFT JOIN categories c ON c.slug = want.slug
`

type InsertItemWantsParams struct {
	ItemID pgtype.UUID
	Wants  []string
}

// LEFT JOIN, а не INNER: неизвестный слаг даёт строку с category_id = NULL и валит вставку.
// INNER молча выбросил бы её, и пользователь получил бы 201 с потерянным желанием.
func (q *Queries) InsertItemWants(ctx context.Context, arg InsertItemWantsParams) error {
	_, err := q.db.Exec(ctx, insertItemWants, arg.ItemID, arg.Wants)
	return err
}

const updateItem = `-- name: UpdateItem :exec
UPDATE items SET
    title       = COALESCE($1, title),
    description = COALESCE($2, description),
    photo_urls  = COALESCE($3::text[], photo_urls),
    category_id = CASE
        WHEN $4::text IS NULL THEN items.category_id
        ELSE (SELECT c.id FROM categories c WHERE c.slug = $4)
    END
WHERE items.id = $5
`

type UpdateItemParams struct {
	Title       pgtype.Text
	Description pgtype.Text
	PhotoUrls   []string
	Category    pgtype.Text
	ID          pgtype.UUID
}

// NULL в аргументе означает «не менять поле» — тот же приём, что в UpdateUserProfile.
// Категория идёт через CASE, а не COALESCE: COALESCE не отличил бы «не передана»
// от «передана несуществующая» и во втором случае молча оставил бы старую.
func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.Exec(ctx, updateItem,
		arg.Title,
		arg.Description,
		arg.PhotoUrls,
		arg.Category,
		arg.ID,
	)
	return err
}
