// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_pickup.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearItemPickupPoint = `-- name: ClearItemPickupPoint :execrows
UPDATE items
SET pickup_point_id = NULL
WHERE id = $1
  AND owner_id = $2
  AND status IN ('available', 'reserved')
`

type ClearItemPickupPointParams struct {
	ItemID  pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) ClearItemPickupPoint(ctx context.Context, arg ClearItemPickupPointParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearItemPickupPoint, arg.ItemID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setItemPickupPoint = `-- name: SetItemPickupPoint :execrows
UPDATE items
SET pickup_point_id = $1
WHERE id = $2
  AND owner_id = $3
  AND status IN ('available', 'reserved')
`

type SetItemPickupPointParams struct {
	PickupPointID pgtype.UUID
	ItemID        pgtype.UUID
	OwnerID       pgtype.UUID
}

// Владелец в WHERE, а не проверкой в Go: чужую вещь запрос просто не найдёт. :execrows
// различает «обновили» и «нечего обновлять», и вызывающий раскладывает ноль в 403/409.
// Статусы traded и withdrawn отсекаются здесь же: вещь вне оборота никуда не несут, а
// отметку завершённого обмена снимает ClearExchangeItemsPickupPoint.
func (q *Queries) SetItemPickupPoint(ctx context.Context, arg SetItemPickupPointParams) (int64, error) {
	result, err := q.db.Exec(ctx, setItemPickupPoint, arg.PickupPointID, arg.ItemID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
