// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_search_visibility.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelProposedExchangesForItemWithdrawal = `-- name: CancelProposedExchangesForItemWithdrawal :many
WITH cancelled AS (
    UPDATE chains AS exchange
    SET status = 'cancelled',
        closed_at = now()
    WHERE exchange.status = 'proposed'
      AND EXISTS (
          SELECT 1
          FROM chain_participants AS participant
          WHERE participant.chain_id = exchange.id
            AND participant.gives_item_id = $1
      )
    RETURNING exchange.id
), events AS (
    INSERT INTO chain_messages (chain_id, kind)
    SELECT cancelled.id, 'exchange_item_withdrawn'
    FROM cancelled
    RETURNING chain_id
)
SELECT DISTINCT
    participant.gives_item_id AS item_id,
    participant.user_id       AS owner_id
FROM cancelled
JOIN events ON events.chain_id = cancelled.id
JOIN chain_participants AS participant ON participant.chain_id = cancelled.id
WHERE participant.gives_item_id <> $1
ORDER BY participant.gives_item_id
`

type CancelProposedExchangesForItemWithdrawalRow struct {
	ItemID  pgtype.UUID
	OwnerID pgtype.UUID
}

// Закрываются только предложения: confirmed/delivering/delivered уже обещали вещь и
// не могут быть отменены обычным снятием объявления. Возвращаем остальные объявления
// затронутых цепочек, чтобы после коммита для них заново запланировать поиск.
func (q *Queries) CancelProposedExchangesForItemWithdrawal(ctx context.Context, itemID pgtype.UUID) ([]CancelProposedExchangesForItemWithdrawalRow, error) {
	rows, err := q.db.Query(ctx, cancelProposedExchangesForItemWithdrawal, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CancelProposedExchangesForItemWithdrawalRow
	for rows.Next() {
		var i CancelProposedExchangesForItemWithdrawalRow
		if err := rows.Scan(&i.ItemID, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemSearchVisibilityForUpdate = `-- name: GetItemSearchVisibilityForUpdate :one
SELECT owner_id, status
FROM items
WHERE id = $1
FOR UPDATE
`

type GetItemSearchVisibilityForUpdateRow struct {
	OwnerID pgtype.UUID
	Status  ItemStatus
}

// После advisory-lock блокируется сама строка. Владелец и текущее состояние читаются
// внутри транзакции, поэтому предварительная проверка HTTP-сервиса не является источником
// истины и не создаёт TOCTOU-гонку.
func (q *Queries) GetItemSearchVisibilityForUpdate(ctx context.Context, itemID pgtype.UUID) (GetItemSearchVisibilityForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getItemSearchVisibilityForUpdate, itemID)
	var i GetItemSearchVisibilityForUpdateRow
	err := row.Scan(&i.OwnerID, &i.Status)
	return i, err
}

const lockItemSearchVisibility = `-- name: LockItemSearchVisibility :exec
SELECT pg_advisory_xact_lock(hashtextextended(($1::uuid)::text, 0))
`

// Снятие объявления использует тот же advisory-lock, что подтверждение обмена и сдача
// вещи в ПВЗ. Поэтому параллельные операции не могут одновременно увидеть available и
// принять несовместимые решения.
func (q *Queries) LockItemSearchVisibility(ctx context.Context, itemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockItemSearchVisibility, itemID)
	return err
}

const publishWithdrawnItem = `-- name: PublishWithdrawnItem :execrows
UPDATE items
SET status = 'available'
WHERE id = $1
  AND owner_id = $2
  AND status = 'withdrawn'
`

type PublishWithdrawnItemParams struct {
	ItemID  pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) PublishWithdrawnItem(ctx context.Context, arg PublishWithdrawnItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, publishWithdrawnItem, arg.ItemID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const withdrawAvailableItem = `-- name: WithdrawAvailableItem :execrows
UPDATE items
SET status = 'withdrawn'
WHERE id = $1
  AND owner_id = $2
  AND status = 'available'
`

type WithdrawAvailableItemParams struct {
	ItemID  pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) WithdrawAvailableItem(ctx context.Context, arg WithdrawAvailableItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, withdrawAvailableItem, arg.ItemID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
