// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChainMessageKind string

const (
	ChainMessageKindText                 ChainMessageKind = "text"
	ChainMessageKindParticipantAccepted  ChainMessageKind = "participant_accepted"
	ChainMessageKindParticipantDeclined  ChainMessageKind = "participant_declined"
	ChainMessageKindParticipantCompleted ChainMessageKind = "participant_completed"
	ChainMessageKindExchangeConfirmed    ChainMessageKind = "exchange_confirmed"
	ChainMessageKindExchangeCompleted    ChainMessageKind = "exchange_completed"
	ChainMessageKindExchangeSuperseded   ChainMessageKind = "exchange_superseded"
)

func (e *ChainMessageKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChainMessageKind(s)
	case string:
		*e = ChainMessageKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ChainMessageKind: %T", src)
	}
	return nil
}

type NullChainMessageKind struct {
	ChainMessageKind ChainMessageKind
	Valid            bool // Valid is true if ChainMessageKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChainMessageKind) Scan(value interface{}) error {
	if value == nil {
		ns.ChainMessageKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChainMessageKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChainMessageKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChainMessageKind), nil
}

type ChainStatus string

const (
	ChainStatusProposed  ChainStatus = "proposed"
	ChainStatusConfirmed ChainStatus = "confirmed"
	ChainStatusCompleted ChainStatus = "completed"
	ChainStatusCancelled ChainStatus = "cancelled"
)

func (e *ChainStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChainStatus(s)
	case string:
		*e = ChainStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChainStatus: %T", src)
	}
	return nil
}

type NullChainStatus struct {
	ChainStatus ChainStatus
	Valid       bool // Valid is true if ChainStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChainStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChainStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChainStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChainStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChainStatus), nil
}

type ItemStatus string

const (
	ItemStatusAvailable ItemStatus = "available"
	ItemStatusReserved  ItemStatus = "reserved"
	ItemStatusTraded    ItemStatus = "traded"
	ItemStatusWithdrawn ItemStatus = "withdrawn"
)

func (e *ItemStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemStatus(s)
	case string:
		*e = ItemStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemStatus: %T", src)
	}
	return nil
}

type NullItemStatus struct {
	ItemStatus ItemStatus
	Valid      bool // Valid is true if ItemStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ItemStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemStatus), nil
}

type ParticipantStatus string

const (
	ParticipantStatusPending  ParticipantStatus = "pending"
	ParticipantStatusAccepted ParticipantStatus = "accepted"
	ParticipantStatusDeclined ParticipantStatus = "declined"
)

func (e *ParticipantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParticipantStatus(s)
	case string:
		*e = ParticipantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ParticipantStatus: %T", src)
	}
	return nil
}

type NullParticipantStatus struct {
	ParticipantStatus ParticipantStatus
	Valid             bool // Valid is true if ParticipantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParticipantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ParticipantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParticipantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParticipantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParticipantStatus), nil
}

type Category struct {
	ID   int16
	Slug string
	Name string
}

type Chain struct {
	ID        pgtype.UUID
	Status    ChainStatus
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ClosedAt  pgtype.Timestamptz
}

type ChainMessage struct {
	ID        pgtype.UUID
	ChainID   pgtype.UUID
	AuthorID  pgtype.UUID
	Kind      ChainMessageKind
	Body      pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type ChainParticipant struct {
	ID                    pgtype.UUID
	ChainID               pgtype.UUID
	UserID                pgtype.UUID
	GivesItemID           pgtype.UUID
	ReceivesItemID        pgtype.UUID
	Position              int32
	Status                ParticipantStatus
	DecidedAt             pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	CompletionConfirmedAt pgtype.Timestamptz
	MessagesReadAt        pgtype.Timestamptz
}

type Item struct {
	ID          pgtype.UUID
	OwnerID     pgtype.UUID
	CategoryID  int16
	Title       string
	Description string
	Status      ItemStatus
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	PhotoUrls   []string
}

type ItemWant struct {
	ItemID     pgtype.UUID
	CategoryID int16
}

type User struct {
	ID             pgtype.UUID
	Nickname       string
	PasswordHash   string
	PhotoUrl       pgtype.Text
	Description    string
	DealsCompleted int32
	DealsBroken    int32
	Rating         pgtype.Numeric
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	IsAdmin        bool
}

type UserBlock struct {
	BlockerID pgtype.UUID
	BlockedID pgtype.UUID
	CreatedAt pgtype.Timestamptz
}
