// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditAction string

const (
	AdminAuditActionReportAssigned       AdminAuditAction = "report_assigned"
	AdminAuditActionReportResolved       AdminAuditAction = "report_resolved"
	AdminAuditActionReportRejected       AdminAuditAction = "report_rejected"
	AdminAuditActionReportMessagesViewed AdminAuditAction = "report_messages_viewed"
	AdminAuditActionUserBlocked          AdminAuditAction = "user_blocked"
	AdminAuditActionUserUnblocked        AdminAuditAction = "user_unblocked"
	AdminAuditActionExchangeCancelled    AdminAuditAction = "exchange_cancelled"
	AdminAuditActionExchangeDelivered    AdminAuditAction = "exchange_delivered"
)

func (e *AdminAuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminAuditAction(s)
	case string:
		*e = AdminAuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminAuditAction: %T", src)
	}
	return nil
}

type NullAdminAuditAction struct {
	AdminAuditAction AdminAuditAction
	Valid            bool // Valid is true if AdminAuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.AdminAuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminAuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminAuditAction), nil
}

type AdminAuditTarget string

const (
	AdminAuditTargetReport   AdminAuditTarget = "report"
	AdminAuditTargetUser     AdminAuditTarget = "user"
	AdminAuditTargetExchange AdminAuditTarget = "exchange"
)

func (e *AdminAuditTarget) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminAuditTarget(s)
	case string:
		*e = AdminAuditTarget(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminAuditTarget: %T", src)
	}
	return nil
}

type NullAdminAuditTarget struct {
	AdminAuditTarget AdminAuditTarget
	Valid            bool // Valid is true if AdminAuditTarget is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminAuditTarget) Scan(value interface{}) error {
	if value == nil {
		ns.AdminAuditTarget, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminAuditTarget.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminAuditTarget) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminAuditTarget), nil
}

type ChainCancelReason string

const (
	ChainCancelReasonProposalDeclined ChainCancelReason = "proposal_declined"
	ChainCancelReasonConfirmedBroken  ChainCancelReason = "confirmed_broken"
	ChainCancelReasonSuperseded       ChainCancelReason = "superseded"
	ChainCancelReasonItemWithdrawn    ChainCancelReason = "item_withdrawn"
	ChainCancelReasonUserBlocked      ChainCancelReason = "user_blocked"
	ChainCancelReasonAdminCancelled   ChainCancelReason = "admin_cancelled"
	ChainCancelReasonLegacy           ChainCancelReason = "legacy"
)

func (e *ChainCancelReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChainCancelReason(s)
	case string:
		*e = ChainCancelReason(s)
	default:
		return fmt.Errorf("unsupported scan type for ChainCancelReason: %T", src)
	}
	return nil
}

type NullChainCancelReason struct {
	ChainCancelReason ChainCancelReason
	Valid             bool // Valid is true if ChainCancelReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChainCancelReason) Scan(value interface{}) error {
	if value == nil {
		ns.ChainCancelReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChainCancelReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChainCancelReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChainCancelReason), nil
}

type ChainMessageKind string

const (
	ChainMessageKindText                     ChainMessageKind = "text"
	ChainMessageKindParticipantAccepted      ChainMessageKind = "participant_accepted"
	ChainMessageKindParticipantDeclined      ChainMessageKind = "participant_declined"
	ChainMessageKindParticipantCompleted     ChainMessageKind = "participant_completed"
	ChainMessageKindExchangeConfirmed        ChainMessageKind = "exchange_confirmed"
	ChainMessageKindExchangeCompleted        ChainMessageKind = "exchange_completed"
	ChainMessageKindExchangeSuperseded       ChainMessageKind = "exchange_superseded"
	ChainMessageKindParticipantDeliveredItem ChainMessageKind = "participant_delivered_item"
	ChainMessageKindExchangeDelivering       ChainMessageKind = "exchange_delivering"
	ChainMessageKindExchangeDelivered        ChainMessageKind = "exchange_delivered"
	ChainMessageKindExchangeItemWithdrawn    ChainMessageKind = "exchange_item_withdrawn"
)

func (e *ChainMessageKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChainMessageKind(s)
	case string:
		*e = ChainMessageKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ChainMessageKind: %T", src)
	}
	return nil
}

type NullChainMessageKind struct {
	ChainMessageKind ChainMessageKind
	Valid            bool // Valid is true if ChainMessageKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChainMessageKind) Scan(value interface{}) error {
	if value == nil {
		ns.ChainMessageKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChainMessageKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChainMessageKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChainMessageKind), nil
}

type ChainStatus string

const (
	ChainStatusProposed   ChainStatus = "proposed"
	ChainStatusConfirmed  ChainStatus = "confirmed"
	ChainStatusDelivering ChainStatus = "delivering"
	ChainStatusDelivered  ChainStatus = "delivered"
	ChainStatusCompleted  ChainStatus = "completed"
	ChainStatusCancelled  ChainStatus = "cancelled"
)

func (e *ChainStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChainStatus(s)
	case string:
		*e = ChainStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChainStatus: %T", src)
	}
	return nil
}

type NullChainStatus struct {
	ChainStatus ChainStatus
	Valid       bool // Valid is true if ChainStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChainStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChainStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChainStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChainStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChainStatus), nil
}

type ItemStatus string

const (
	ItemStatusAvailable ItemStatus = "available"
	ItemStatusReserved  ItemStatus = "reserved"
	ItemStatusTraded    ItemStatus = "traded"
	ItemStatusWithdrawn ItemStatus = "withdrawn"
)

func (e *ItemStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemStatus(s)
	case string:
		*e = ItemStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemStatus: %T", src)
	}
	return nil
}

type NullItemStatus struct {
	ItemStatus ItemStatus
	Valid      bool // Valid is true if ItemStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ItemStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemStatus), nil
}

type ParticipantStatus string

const (
	ParticipantStatusPending  ParticipantStatus = "pending"
	ParticipantStatusAccepted ParticipantStatus = "accepted"
	ParticipantStatusDeclined ParticipantStatus = "declined"
)

func (e *ParticipantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParticipantStatus(s)
	case string:
		*e = ParticipantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ParticipantStatus: %T", src)
	}
	return nil
}

type NullParticipantStatus struct {
	ParticipantStatus ParticipantStatus
	Valid             bool // Valid is true if ParticipantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParticipantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ParticipantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParticipantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParticipantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParticipantStatus), nil
}

type ReportReason string

const (
	ReportReasonSpam  ReportReason = "spam"
	ReportReasonAbuse ReportReason = "abuse"
	ReportReasonOther ReportReason = "other"
)

func (e *ReportReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportReason(s)
	case string:
		*e = ReportReason(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportReason: %T", src)
	}
	return nil
}

type NullReportReason struct {
	ReportReason ReportReason
	Valid        bool // Valid is true if ReportReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportReason) Scan(value interface{}) error {
	if value == nil {
		ns.ReportReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportReason), nil
}

type ReportStatus string

const (
	ReportStatusOpen     ReportStatus = "open"
	ReportStatusResolved ReportStatus = "resolved"
	ReportStatusRejected ReportStatus = "rejected"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus
	Valid        bool // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

type SupportThreadStatus string

const (
	SupportThreadStatusOpen       SupportThreadStatus = "open"
	SupportThreadStatusInProgress SupportThreadStatus = "in_progress"
	SupportThreadStatusClosed     SupportThreadStatus = "closed"
)

func (e *SupportThreadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SupportThreadStatus(s)
	case string:
		*e = SupportThreadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SupportThreadStatus: %T", src)
	}
	return nil
}

type NullSupportThreadStatus struct {
	SupportThreadStatus SupportThreadStatus
	Valid               bool // Valid is true if SupportThreadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSupportThreadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SupportThreadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SupportThreadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSupportThreadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SupportThreadStatus), nil
}

type AdminAuditLog struct {
	ID         pgtype.UUID
	AdminID    pgtype.UUID
	Action     AdminAuditAction
	TargetType AdminAuditTarget
	TargetID   pgtype.UUID
	Metadata   []byte
	CreatedAt  pgtype.Timestamptz
}

type BrokenExchangeComposition struct {
	CompositionKey string
	SourceChainID  pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type Category struct {
	ID   int16
	Slug string
	Name string
}

type Chain struct {
	ID             pgtype.UUID
	Status         ChainStatus
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ClosedAt       pgtype.Timestamptz
	Signature      string
	CompositionKey string
	CancelReason   NullChainCancelReason
}

type ChainMessage struct {
	ID        pgtype.UUID
	ChainID   pgtype.UUID
	AuthorID  pgtype.UUID
	Kind      ChainMessageKind
	Body      pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type ChainParticipant struct {
	ID                    pgtype.UUID
	ChainID               pgtype.UUID
	UserID                pgtype.UUID
	GivesItemID           pgtype.UUID
	ReceivesItemID        pgtype.UUID
	Position              int32
	Status                ParticipantStatus
	DecidedAt             pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	CompletionConfirmedAt pgtype.Timestamptz
	MessagesReadAt        pgtype.Timestamptz
}

type Item struct {
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
	CategoryID    int16
	Title         string
	Description   string
	Status        ItemStatus
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	PhotoUrls     []string
	PickupPointID pgtype.UUID
}

type ItemRefusal struct {
	UserID    pgtype.UUID
	ItemID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type ItemWant struct {
	ItemID     pgtype.UUID
	CategoryID int16
}

type Notification struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	ChainID          pgtype.UUID
	MessageID        pgtype.UUID
	Kind             string
	ReadAt           pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	SupportThreadID  pgtype.UUID
	SupportMessageID pgtype.UUID
}

type PickupPoint struct {
	ID        pgtype.UUID
	Name      string
	Address   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Report struct {
	ID                pgtype.UUID
	ReporterID        pgtype.UUID
	MessageID         pgtype.UUID
	Reason            ReportReason
	Comment           string
	Status            ReportStatus
	AssigneeID        pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	AssignedAt        pgtype.Timestamptz
	ClosedAt          pgtype.Timestamptz
	ResolutionComment string
}

type SupportMessage struct {
	ID        pgtype.UUID
	ThreadID  pgtype.UUID
	AuthorID  pgtype.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
}

type SupportThread struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Subject         string
	Status          SupportThreadStatus
	AssignedAdminID pgtype.UUID
	UserReadAt      pgtype.Timestamptz
	AdminReadAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ClosedAt        pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	Nickname       string
	PasswordHash   string
	PhotoUrl       pgtype.Text
	Description    string
	DealsCompleted int32
	DealsBroken    int32
	Rating         pgtype.Numeric
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	IsAdmin        bool
	IsBlocked      bool
	BlockedAt      pgtype.Timestamptz
	BlockedBy      pgtype.UUID
}

type UserBlock struct {
	BlockerID pgtype.UUID
	BlockedID pgtype.UUID
	CreatedAt pgtype.Timestamptz
}
