// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)
FROM notifications
WHERE user_id = $1
  AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT
    notification.id,
    notification.chain_id,
    notification.support_thread_id,
    COALESCE(notification.message_id, notification.support_message_id) AS message_id,
    notification.kind,
    COALESCE(message.author_id, support_message.author_id) AS author_id,
    author.nickname AS author_nickname,
    author.photo_url AS author_photo_url,
    COALESCE(exchange.status::text, '') AS exchange_status,
    gives_item.title AS gives_item_title,
    receives_item.title AS receives_item_title,
    support_thread.subject AS support_subject,
    notification.read_at,
    notification.created_at
FROM notifications AS notification
LEFT JOIN chains AS exchange
    ON exchange.id = notification.chain_id
LEFT JOIN chain_participants AS current_participant
    ON current_participant.chain_id = notification.chain_id
   AND current_participant.user_id = notification.user_id
LEFT JOIN items AS gives_item
    ON gives_item.id = current_participant.gives_item_id
LEFT JOIN items AS receives_item
    ON receives_item.id = current_participant.receives_item_id
LEFT JOIN chain_messages AS message
    ON message.id = notification.message_id
LEFT JOIN support_threads AS support_thread
    ON support_thread.id = notification.support_thread_id
LEFT JOIN support_messages AS support_message
    ON support_message.id = notification.support_message_id
LEFT JOIN users AS author
    ON author.id = COALESCE(message.author_id, support_message.author_id)
WHERE notification.user_id = $1
  AND (NOT $2::boolean OR notification.read_at IS NULL)
ORDER BY notification.created_at DESC, notification.id DESC
LIMIT $4
OFFSET $3
`

type ListNotificationsParams struct {
	UserID     pgtype.UUID
	UnreadOnly bool
	PageOffset int32
	PageLimit  int32
}

type ListNotificationsRow struct {
	ID                pgtype.UUID
	ChainID           pgtype.UUID
	SupportThreadID   pgtype.UUID
	MessageID         pgtype.UUID
	Kind              string
	AuthorID          pgtype.UUID
	AuthorNickname    pgtype.Text
	AuthorPhotoUrl    pgtype.Text
	ExchangeStatus    interface{}
	GivesItemTitle    pgtype.Text
	ReceivesItemTitle pgtype.Text
	SupportSubject    pgtype.Text
	ReadAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.SupportThreadID,
			&i.MessageID,
			&i.Kind,
			&i.AuthorID,
			&i.AuthorNickname,
			&i.AuthorPhotoUrl,
			&i.ExchangeStatus,
			&i.GivesItemTitle,
			&i.ReceivesItemTitle,
			&i.SupportSubject,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET read_at = clock_timestamp()
WHERE user_id = $1
  AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications
SET read_at = COALESCE(read_at, clock_timestamp())
WHERE id = $1
  AND user_id = $2
`

type MarkNotificationReadParams struct {
	NotificationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.NotificationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
