// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pickup_points.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPickupPoint = `-- name: CreatePickupPoint :one
INSERT INTO pickup_points (name, address)
VALUES ($1, $2)
RETURNING id, name, address, created_at, updated_at
`

type CreatePickupPointParams struct {
	Name    string
	Address string
}

func (q *Queries) CreatePickupPoint(ctx context.Context, arg CreatePickupPointParams) (PickupPoint, error) {
	row := q.db.QueryRow(ctx, createPickupPoint, arg.Name, arg.Address)
	var i PickupPoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePickupPoint = `-- name: DeletePickupPoint :execrows
DELETE FROM pickup_points
WHERE id = $1
`

// :execrows позволяет отличить успешное удаление от отсутствующего ПВЗ.
// Будущий items.pickup_point_id должен ссылаться сюда с ON DELETE RESTRICT:
// repository уже переводит нарушение этого FK в ErrInUse.
func (q *Queries) DeletePickupPoint(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePickupPoint, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPickupPointByID = `-- name: GetPickupPointByID :one
SELECT id, name, address, created_at, updated_at
FROM pickup_points
WHERE id = $1
`

func (q *Queries) GetPickupPointByID(ctx context.Context, id pgtype.UUID) (PickupPoint, error) {
	row := q.db.QueryRow(ctx, getPickupPointByID, id)
	var i PickupPoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPickupPoints = `-- name: ListPickupPoints :many
SELECT id, name, address, created_at, updated_at
FROM pickup_points
ORDER BY created_at DESC, id
`

func (q *Queries) ListPickupPoints(ctx context.Context) ([]PickupPoint, error) {
	rows, err := q.db.Query(ctx, listPickupPoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PickupPoint
	for rows.Next() {
		var i PickupPoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePickupPoint = `-- name: UpdatePickupPoint :one
UPDATE pickup_points SET
    name    = COALESCE($1, name),
    address = COALESCE($2, address)
WHERE id = $3
RETURNING id, name, address, created_at, updated_at
`

type UpdatePickupPointParams struct {
	Name    pgtype.Text
	Address pgtype.Text
	ID      pgtype.UUID
}

// NULL означает «поле не передали». Пустые значения раньше отсекает service,
// а CHECK в таблице остаётся последней защитой от обхода HTTP API.
func (q *Queries) UpdatePickupPoint(ctx context.Context, arg UpdatePickupPointParams) (PickupPoint, error) {
	row := q.db.QueryRow(ctx, updatePickupPoint, arg.Name, arg.Address, arg.ID)
	var i PickupPoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
