// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExchangeRatingEligibility = `-- name: GetExchangeRatingEligibility :one
SELECT
    exchange.status AS exchange_status,
    (exchange.closed_at > now() - interval '14 days')::boolean AS window_open,
    (rater.user_id IS NOT NULL)::boolean AS is_participant
FROM chains AS exchange
LEFT JOIN chain_participants AS rater
    ON rater.chain_id = exchange.id
   AND rater.user_id = $1
WHERE exchange.id = $2
`

type GetExchangeRatingEligibilityParams struct {
	RaterID    pgtype.UUID
	ExchangeID pgtype.UUID
}

type GetExchangeRatingEligibilityRow struct {
	ExchangeStatus ChainStatus
	WindowOpen     bool
	IsParticipant  bool
}

// Зачем оценка не прошла: обмена нет (ноль строк), не участник, не завершён или окно
// закрылось. Нужен только для выбора кода ответа после неудачного upsert'а, поэтому
// ничего сверх этого не читает — состояние оценки клиент и так видит в самом обмене.
//
// Окно приезжает готовым ответом, а не сроком: сравнивал бы его Go — в проверке
// появились бы вторые часы, расходящиеся с теми, по которым отказал сам upsert.
func (q *Queries) GetExchangeRatingEligibility(ctx context.Context, arg GetExchangeRatingEligibilityParams) (GetExchangeRatingEligibilityRow, error) {
	row := q.db.QueryRow(ctx, getExchangeRatingEligibility, arg.RaterID, arg.ExchangeID)
	var i GetExchangeRatingEligibilityRow
	err := row.Scan(&i.ExchangeStatus, &i.WindowOpen, &i.IsParticipant)
	return i, err
}

const listUserRatings = `-- name: ListUserRatings :many
SELECT score, comment, created_at
FROM chain_ratings
WHERE rated_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListUserRatingsParams struct {
	RatedID    pgtype.UUID
	PageOffset int32
	PageLimit  int32
}

type ListUserRatingsRow struct {
	Score     int16
	Comment   string
	CreatedAt pgtype.Timestamptz
}

// Лента отзывов о человеке. Анонимная: ни автора, ни цепочки, ни id самой оценки, ни
// времени правки — всё это каналы, по которым автор вычисляется. Общее число не считаем:
// оно уже лежит в users.ratings_count того же профиля.
func (q *Queries) ListUserRatings(ctx context.Context, arg ListUserRatingsParams) ([]ListUserRatingsRow, error) {
	rows, err := q.db.Query(ctx, listUserRatings, arg.RatedID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRatingsRow
	for rows.Next() {
		var i ListUserRatingsRow
		if err := rows.Scan(&i.Score, &i.Comment, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRating = `-- name: UpsertExchangeRating :one
INSERT INTO chain_ratings (chain_id, rater_id, rated_id, score, comment)
SELECT
    rater.chain_id,
    rater.user_id,
    rated.user_id,
    $1::smallint,
    $2::text
FROM chain_participants AS rater
JOIN chains AS exchange
    ON exchange.id = rater.chain_id
JOIN chain_participants AS rated
    ON rated.chain_id = rater.chain_id
   AND rated.gives_item_id = rater.receives_item_id
WHERE rater.chain_id = $3
  AND rater.user_id = $4
  AND exchange.status = 'completed'
  -- closed_at IS NULL даёт false и закрывает окно: у завершённого обмена он всегда есть,
  -- а если когда-то не окажется — отказ безопаснее вечно открытой оценки.
  AND exchange.closed_at > now() - interval '14 days'
ON CONFLICT (chain_id, rater_id) DO UPDATE
SET score   = EXCLUDED.score,
    comment = EXCLUDED.comment
RETURNING rated_id, score, comment, created_at, updated_at
`

type UpsertExchangeRatingParams struct {
	Score      int16
	Comment    string
	ExchangeID pgtype.UUID
	RaterID    pgtype.UUID
}

type UpsertExchangeRatingRow struct {
	RatedID   pgtype.UUID
	Score     int16
	Comment   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Кого оценивают, клиент не передаёт: партнёр выводится из самого цикла — это участник,
// чья отдаваемая вещь пришла ко мне. Меньше полей в запросе, и целый класс проверок
// («а можно ли оценивать этого?») перестаёт существовать.
//
// Все условия висят на SELECT, который питает INSERT. Когда он отдаёт ноль строк, INSERT
// не выполняется, а значит и ON CONFLICT не срабатывает: просроченное окно и незавершённый
// обмен блокируют не только первую оценку, но и правку уже поставленной.
//
// Ноль строк на выходе означает «одна из проверок не прошла» и не говорит какая:
// разбирается в этом отдельный GetExchangeRatingEligibility, и только когда что-то пошло
// не так. Счастливый путь остаётся одним запросом.
func (q *Queries) UpsertExchangeRating(ctx context.Context, arg UpsertExchangeRatingParams) (UpsertExchangeRatingRow, error) {
	row := q.db.QueryRow(ctx, upsertExchangeRating,
		arg.Score,
		arg.Comment,
		arg.ExchangeID,
		arg.RaterID,
	)
	var i UpsertExchangeRatingRow
	err := row.Scan(
		&i.RatedID,
		&i.Score,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
