// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (reporter_id, message_id, reason, comment)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, reporter_id, message_id, reason, comment, status, assignee_id, created_at
`

type CreateReportParams struct {
	ReporterID pgtype.UUID
	MessageID  pgtype.UUID
	Reason     ReportReason
	Comment    string
}

// Повтор ловится UNIQUE (reporter_id, message_id), а не проверкой перед вставкой:
// две открытые вкладки не создадут двух жалоб.
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.MessageID,
		arg.Reason,
		arg.Comment,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.MessageID,
		&i.Reason,
		&i.Comment,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedAt,
	)
	return i, err
}

const getReportTarget = `-- name: GetReportTarget :one
SELECT
    message.kind,
    message.author_id,
    EXISTS (
        SELECT 1
        FROM chain_participants AS participant
        WHERE participant.chain_id = message.chain_id
          AND participant.user_id = $1
    ) AS is_participant
FROM chain_messages AS message
WHERE message.id = $2
`

type GetReportTargetParams struct {
	UserID    pgtype.UUID
	MessageID pgtype.UUID
}

type GetReportTargetRow struct {
	Kind          ChainMessageKind
	AuthorID      pgtype.UUID
	IsParticipant bool
}

// Цель жалобы и право на неё — за один запрос, как GetExchangeAccess перед записью
// в тред. Вставка с WHERE вернула бы ноль строк без причины, а причин отказа три и у
// каждой свой код ответа: посторонний, собственное сообщение и событие обмена.
func (q *Queries) GetReportTarget(ctx context.Context, arg GetReportTargetParams) (GetReportTargetRow, error) {
	row := q.db.QueryRow(ctx, getReportTarget, arg.UserID, arg.MessageID)
	var i GetReportTargetRow
	err := row.Scan(&i.Kind, &i.AuthorID, &i.IsParticipant)
	return i, err
}
