// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: support.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignSupportThread = `-- name: AssignSupportThread :execrows
UPDATE support_threads
SET assigned_admin_id = $1,
    status = 'in_progress',
    updated_at = clock_timestamp()
WHERE id = $2
  AND status = 'open'
  AND assigned_admin_id IS NULL
`

type AssignSupportThreadParams struct {
	AdminID  pgtype.UUID
	ThreadID pgtype.UUID
}

func (q *Queries) AssignSupportThread(ctx context.Context, arg AssignSupportThreadParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignSupportThread, arg.AdminID, arg.ThreadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeSupportThreadByAdmin = `-- name: CloseSupportThreadByAdmin :execrows
UPDATE support_threads
SET status = 'closed',
    closed_at = clock_timestamp(),
    updated_at = clock_timestamp()
WHERE id = $1
  AND assigned_admin_id = $2
  AND status = 'in_progress'
`

type CloseSupportThreadByAdminParams struct {
	ThreadID pgtype.UUID
	AdminID  pgtype.UUID
}

func (q *Queries) CloseSupportThreadByAdmin(ctx context.Context, arg CloseSupportThreadByAdminParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeSupportThreadByAdmin, arg.ThreadID, arg.AdminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeSupportThreadByUser = `-- name: CloseSupportThreadByUser :execrows
UPDATE support_threads
SET status = 'closed',
    closed_at = clock_timestamp(),
    updated_at = clock_timestamp()
WHERE id = $1
  AND user_id = $2
  AND status <> 'closed'
`

type CloseSupportThreadByUserParams struct {
	ThreadID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) CloseSupportThreadByUser(ctx context.Context, arg CloseSupportThreadByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeSupportThreadByUser, arg.ThreadID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAdminSupportThreads = `-- name: CountAdminSupportThreads :one
SELECT count(*)
FROM support_threads
WHERE ($1::text = '' OR status::text = $1)
`

func (q *Queries) CountAdminSupportThreads(ctx context.Context, statusFilter string) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminSupportThreads, statusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminSupportMessage = `-- name: CreateAdminSupportMessage :one
WITH created AS (
    INSERT INTO support_messages (thread_id, author_id, body)
    SELECT thread.id, $1, $2
    FROM support_threads AS thread
    WHERE thread.id = $3
      AND thread.assigned_admin_id = $1
      AND thread.status = 'in_progress'
    RETURNING id, thread_id, author_id, body, created_at
), touched AS (
    UPDATE support_threads AS thread
    SET updated_at = created.created_at,
        admin_read_at = created.created_at
    FROM created
    WHERE thread.id = created.thread_id
)
SELECT
    created.id,
    created.thread_id,
    created.author_id,
    created.body,
    created.created_at
FROM created
`

type CreateAdminSupportMessageParams struct {
	AdminID  pgtype.UUID
	Body     string
	ThreadID pgtype.UUID
}

type CreateAdminSupportMessageRow struct {
	ID        pgtype.UUID
	ThreadID  pgtype.UUID
	AuthorID  pgtype.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAdminSupportMessage(ctx context.Context, arg CreateAdminSupportMessageParams) (CreateAdminSupportMessageRow, error) {
	row := q.db.QueryRow(ctx, createAdminSupportMessage, arg.AdminID, arg.Body, arg.ThreadID)
	var i CreateAdminSupportMessageRow
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createSupportThread = `-- name: CreateSupportThread :one
WITH created_thread AS (
    INSERT INTO support_threads (user_id, subject)
    VALUES ($1, $2)
    RETURNING id, user_id, subject, status, assigned_admin_id, user_read_at, admin_read_at, created_at, updated_at, closed_at
), created_message AS (
    INSERT INTO support_messages (thread_id, author_id, body)
    SELECT id, user_id, $3
    FROM created_thread
    RETURNING id, created_at
)
SELECT
    thread.id,
    thread.user_id,
    thread.subject,
    thread.status,
    thread.assigned_admin_id,
    thread.created_at,
    thread.updated_at,
    message.id AS first_message_id,
    message.created_at AS first_message_created_at
FROM created_thread AS thread
JOIN created_message AS message ON true
`

type CreateSupportThreadParams struct {
	UserID  pgtype.UUID
	Subject string
	Body    string
}

type CreateSupportThreadRow struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	Subject               string
	Status                SupportThreadStatus
	AssignedAdminID       pgtype.UUID
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	FirstMessageID        pgtype.UUID
	FirstMessageCreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateSupportThread(ctx context.Context, arg CreateSupportThreadParams) (CreateSupportThreadRow, error) {
	row := q.db.QueryRow(ctx, createSupportThread, arg.UserID, arg.Subject, arg.Body)
	var i CreateSupportThreadRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject,
		&i.Status,
		&i.AssignedAdminID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstMessageID,
		&i.FirstMessageCreatedAt,
	)
	return i, err
}

const createUserSupportMessage = `-- name: CreateUserSupportMessage :one
WITH created AS (
    INSERT INTO support_messages (thread_id, author_id, body)
    SELECT thread.id, $1, $2
    FROM support_threads AS thread
    WHERE thread.id = $3
      AND thread.user_id = $1
      AND thread.status <> 'closed'
    RETURNING id, thread_id, author_id, body, created_at
), touched AS (
    UPDATE support_threads AS thread
    SET updated_at = created.created_at,
        user_read_at = created.created_at
    FROM created
    WHERE thread.id = created.thread_id
)
SELECT
    created.id,
    created.thread_id,
    created.author_id,
    created.body,
    created.created_at
FROM created
`

type CreateUserSupportMessageParams struct {
	UserID   pgtype.UUID
	Body     string
	ThreadID pgtype.UUID
}

type CreateUserSupportMessageRow struct {
	ID        pgtype.UUID
	ThreadID  pgtype.UUID
	AuthorID  pgtype.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUserSupportMessage(ctx context.Context, arg CreateUserSupportMessageParams) (CreateUserSupportMessageRow, error) {
	row := q.db.QueryRow(ctx, createUserSupportMessage, arg.UserID, arg.Body, arg.ThreadID)
	var i CreateUserSupportMessageRow
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminSupportThread = `-- name: GetAdminSupportThread :one
SELECT
    thread.id,
    thread.user_id,
    customer.nickname AS user_nickname,
    customer.photo_url AS user_photo_url,
    thread.subject,
    thread.status,
    thread.assigned_admin_id,
    admin.nickname AS assigned_admin_nickname,
    thread.created_at,
    thread.updated_at,
    thread.closed_at
FROM support_threads AS thread
JOIN users AS customer ON customer.id = thread.user_id
LEFT JOIN users AS admin ON admin.id = thread.assigned_admin_id
WHERE thread.id = $1
`

type GetAdminSupportThreadRow struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	UserNickname          string
	UserPhotoUrl          pgtype.Text
	Subject               string
	Status                SupportThreadStatus
	AssignedAdminID       pgtype.UUID
	AssignedAdminNickname pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ClosedAt              pgtype.Timestamptz
}

func (q *Queries) GetAdminSupportThread(ctx context.Context, threadID pgtype.UUID) (GetAdminSupportThreadRow, error) {
	row := q.db.QueryRow(ctx, getAdminSupportThread, threadID)
	var i GetAdminSupportThreadRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserNickname,
		&i.UserPhotoUrl,
		&i.Subject,
		&i.Status,
		&i.AssignedAdminID,
		&i.AssignedAdminNickname,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getUserSupportThread = `-- name: GetUserSupportThread :one
SELECT
    thread.id,
    thread.user_id,
    thread.subject,
    thread.status,
    thread.assigned_admin_id,
    admin.nickname AS assigned_admin_nickname,
    thread.created_at,
    thread.updated_at,
    thread.closed_at
FROM support_threads AS thread
LEFT JOIN users AS admin ON admin.id = thread.assigned_admin_id
WHERE thread.id = $1
  AND thread.user_id = $2
`

type GetUserSupportThreadParams struct {
	ThreadID pgtype.UUID
	UserID   pgtype.UUID
}

type GetUserSupportThreadRow struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	Subject               string
	Status                SupportThreadStatus
	AssignedAdminID       pgtype.UUID
	AssignedAdminNickname pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ClosedAt              pgtype.Timestamptz
}

func (q *Queries) GetUserSupportThread(ctx context.Context, arg GetUserSupportThreadParams) (GetUserSupportThreadRow, error) {
	row := q.db.QueryRow(ctx, getUserSupportThread, arg.ThreadID, arg.UserID)
	var i GetUserSupportThreadRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject,
		&i.Status,
		&i.AssignedAdminID,
		&i.AssignedAdminNickname,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listAdminSupportThreads = `-- name: ListAdminSupportThreads :many
SELECT
    thread.id,
    thread.user_id,
    customer.nickname AS user_nickname,
    customer.photo_url AS user_photo_url,
    thread.subject,
    thread.status,
    thread.assigned_admin_id,
    admin.nickname AS assigned_admin_nickname,
    thread.created_at,
    thread.updated_at,
    thread.closed_at,
    last_message.body AS last_message_body,
    last_message.created_at AS last_message_created_at,
    count(unread.id) AS unread_count
FROM support_threads AS thread
JOIN users AS customer ON customer.id = thread.user_id
LEFT JOIN users AS admin ON admin.id = thread.assigned_admin_id
LEFT JOIN LATERAL (
    SELECT message.body, message.created_at
    FROM support_messages AS message
    WHERE message.thread_id = thread.id
    ORDER BY message.created_at DESC, message.id DESC
    LIMIT 1
) AS last_message ON true
LEFT JOIN support_messages AS unread
    ON unread.thread_id = thread.id
   AND unread.created_at > COALESCE(thread.admin_read_at, '-infinity'::timestamptz)
   AND unread.author_id = thread.user_id
WHERE ($1::text = '' OR thread.status::text = $1)
GROUP BY thread.id, customer.nickname, customer.photo_url, admin.nickname,
         last_message.body, last_message.created_at
ORDER BY
    CASE thread.status WHEN 'open' THEN 0 WHEN 'in_progress' THEN 1 ELSE 2 END,
    thread.updated_at DESC,
    thread.id DESC
LIMIT $3
OFFSET $2
`

type ListAdminSupportThreadsParams struct {
	StatusFilter string
	PageOffset   int32
	PageLimit    int32
}

type ListAdminSupportThreadsRow struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	UserNickname          string
	UserPhotoUrl          pgtype.Text
	Subject               string
	Status                SupportThreadStatus
	AssignedAdminID       pgtype.UUID
	AssignedAdminNickname pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ClosedAt              pgtype.Timestamptz
	LastMessageBody       string
	LastMessageCreatedAt  pgtype.Timestamptz
	UnreadCount           int64
}

func (q *Queries) ListAdminSupportThreads(ctx context.Context, arg ListAdminSupportThreadsParams) ([]ListAdminSupportThreadsRow, error) {
	rows, err := q.db.Query(ctx, listAdminSupportThreads, arg.StatusFilter, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminSupportThreadsRow
	for rows.Next() {
		var i ListAdminSupportThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserNickname,
			&i.UserPhotoUrl,
			&i.Subject,
			&i.Status,
			&i.AssignedAdminID,
			&i.AssignedAdminNickname,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.LastMessageBody,
			&i.LastMessageCreatedAt,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupportMessages = `-- name: ListSupportMessages :many
SELECT
    message.id,
    message.thread_id,
    message.body,
    message.created_at,
    author.id AS author_id,
    author.nickname AS author_nickname,
    author.photo_url AS author_photo_url,
    author.is_admin AS author_is_admin
FROM support_messages AS message
JOIN users AS author ON author.id = message.author_id
WHERE message.thread_id = $1
ORDER BY message.created_at, message.id
`

type ListSupportMessagesRow struct {
	ID             pgtype.UUID
	ThreadID       pgtype.UUID
	Body           string
	CreatedAt      pgtype.Timestamptz
	AuthorID       pgtype.UUID
	AuthorNickname string
	AuthorPhotoUrl pgtype.Text
	AuthorIsAdmin  bool
}

func (q *Queries) ListSupportMessages(ctx context.Context, threadID pgtype.UUID) ([]ListSupportMessagesRow, error) {
	rows, err := q.db.Query(ctx, listSupportMessages, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupportMessagesRow
	for rows.Next() {
		var i ListSupportMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorNickname,
			&i.AuthorPhotoUrl,
			&i.AuthorIsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSupportThreads = `-- name: ListUserSupportThreads :many
SELECT
    thread.id,
    thread.subject,
    thread.status,
    thread.assigned_admin_id,
    admin.nickname AS assigned_admin_nickname,
    thread.created_at,
    thread.updated_at,
    thread.closed_at,
    last_message.body AS last_message_body,
    last_message.created_at AS last_message_created_at,
    count(unread.id) AS unread_count
FROM support_threads AS thread
LEFT JOIN users AS admin
    ON admin.id = thread.assigned_admin_id
LEFT JOIN LATERAL (
    SELECT message.body, message.created_at
    FROM support_messages AS message
    WHERE message.thread_id = thread.id
    ORDER BY message.created_at DESC, message.id DESC
    LIMIT 1
) AS last_message ON true
LEFT JOIN support_messages AS unread
    ON unread.thread_id = thread.id
   AND unread.created_at > COALESCE(thread.user_read_at, '-infinity'::timestamptz)
   AND unread.author_id <> thread.user_id
WHERE thread.user_id = $1
GROUP BY thread.id, admin.nickname, last_message.body, last_message.created_at
ORDER BY thread.updated_at DESC, thread.id DESC
`

type ListUserSupportThreadsRow struct {
	ID                    pgtype.UUID
	Subject               string
	Status                SupportThreadStatus
	AssignedAdminID       pgtype.UUID
	AssignedAdminNickname pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ClosedAt              pgtype.Timestamptz
	LastMessageBody       string
	LastMessageCreatedAt  pgtype.Timestamptz
	UnreadCount           int64
}

func (q *Queries) ListUserSupportThreads(ctx context.Context, userID pgtype.UUID) ([]ListUserSupportThreadsRow, error) {
	rows, err := q.db.Query(ctx, listUserSupportThreads, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSupportThreadsRow
	for rows.Next() {
		var i ListUserSupportThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Status,
			&i.AssignedAdminID,
			&i.AssignedAdminNickname,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.LastMessageBody,
			&i.LastMessageCreatedAt,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSupportThreadReadByAdmin = `-- name: MarkSupportThreadReadByAdmin :execrows
UPDATE support_threads
SET admin_read_at = clock_timestamp()
WHERE id = $1
`

func (q *Queries) MarkSupportThreadReadByAdmin(ctx context.Context, threadID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSupportThreadReadByAdmin, threadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSupportThreadReadByUser = `-- name: MarkSupportThreadReadByUser :execrows
UPDATE support_threads
SET user_read_at = clock_timestamp()
WHERE id = $1
  AND user_id = $2
`

type MarkSupportThreadReadByUserParams struct {
	ThreadID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) MarkSupportThreadReadByUser(ctx context.Context, arg MarkSupportThreadReadByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSupportThreadReadByUser, arg.ThreadID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
