// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_blocks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserBlockAndCancelProposals = `-- name: AddUserBlockAndCancelProposals :execrows
WITH inserted_block AS (
    INSERT INTO user_blocks (blocker_id, blocked_id)
    VALUES ($1, $2)
    ON CONFLICT (blocker_id, blocked_id) DO NOTHING
    RETURNING blocker_id
)
UPDATE chains AS exchange
SET status = 'cancelled',
    closed_at = now()
WHERE exchange.status = 'proposed'
  AND EXISTS (
      SELECT 1
      FROM chain_participants AS participant
      WHERE participant.chain_id = exchange.id
        AND participant.user_id = $1
  )
  AND EXISTS (
      SELECT 1
      FROM chain_participants AS participant
      WHERE participant.chain_id = exchange.id
        AND participant.user_id = $2
  )
`

type AddUserBlockAndCancelProposalsParams struct {
	BlockerID pgtype.UUID
	BlockedID pgtype.UUID
}

// Блокировка и отмена ещё не подтверждённых совместных обменов выполняются одним
// SQL-выражением, то есть атомарно. Подтверждённые и завершённые обмены не меняются.
func (q *Queries) AddUserBlockAndCancelProposals(ctx context.Context, arg AddUserBlockAndCancelProposalsParams) (int64, error) {
	result, err := q.db.Exec(ctx, addUserBlockAndCancelProposals, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserBlock = `-- name: DeleteUserBlock :exec
DELETE FROM user_blocks
WHERE blocker_id = $1
  AND blocked_id = $2
`

type DeleteUserBlockParams struct {
	BlockerID pgtype.UUID
	BlockedID pgtype.UUID
}

// Повторное удаление безопасно: отсутствие строки не считается ошибкой.
func (q *Queries) DeleteUserBlock(ctx context.Context, arg DeleteUserBlockParams) error {
	_, err := q.db.Exec(ctx, deleteUserBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const listUserBlocks = `-- name: ListUserBlocks :many
SELECT
    blocked_user.id,
    blocked_user.nickname,
    blocked_user.photo_url,
    block.created_at AS blocked_at
FROM user_blocks AS block
JOIN users AS blocked_user
  ON blocked_user.id = block.blocked_id
WHERE block.blocker_id = $1
ORDER BY block.created_at DESC, blocked_user.id
`

type ListUserBlocksRow struct {
	ID        pgtype.UUID
	Nickname  string
	PhotoUrl  pgtype.Text
	BlockedAt pgtype.Timestamptz
}

func (q *Queries) ListUserBlocks(ctx context.Context, blockerID pgtype.UUID) ([]ListUserBlocksRow, error) {
	rows, err := q.db.Query(ctx, listUserBlocks, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserBlocksRow
	for rows.Next() {
		var i ListUserBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.PhotoUrl,
			&i.BlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
