// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (nickname, password_hash, photo_url, description)
VALUES ($1, $2, $3, $4)
RETURNING id, nickname, password_hash, photo_url, description, deals_completed, deals_broken, rating, created_at, updated_at, is_admin, is_blocked, blocked_at, blocked_by, ratings_count
`

type CreateUserParams struct {
	Nickname     string
	PasswordHash string
	PhotoUrl     pgtype.Text
	Description  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Nickname,
		arg.PasswordHash,
		arg.PhotoUrl,
		arg.Description,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.PasswordHash,
		&i.PhotoUrl,
		&i.Description,
		&i.DealsCompleted,
		&i.DealsBroken,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.BlockedBy,
		&i.RatingsCount,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, nickname, password_hash, photo_url, description, deals_completed, deals_broken, rating, created_at, updated_at, is_admin, is_blocked, blocked_at, blocked_by, ratings_count FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.PasswordHash,
		&i.PhotoUrl,
		&i.Description,
		&i.DealsCompleted,
		&i.DealsBroken,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.BlockedBy,
		&i.RatingsCount,
	)
	return i, err
}

const getUserByNickname = `-- name: GetUserByNickname :one
SELECT id, nickname, password_hash, photo_url, description, deals_completed, deals_broken, rating, created_at, updated_at, is_admin, is_blocked, blocked_at, blocked_by, ratings_count FROM users WHERE lower(nickname) = lower($1)
`

// Логин: nickname уникален регистронезависимо, запрос обязан идти через lower(),
// иначе не попадёт в users_nickname_lower_key.
func (q *Queries) GetUserByNickname(ctx context.Context, nickname string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByNickname, nickname)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.PasswordHash,
		&i.PhotoUrl,
		&i.Description,
		&i.DealsCompleted,
		&i.DealsBroken,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.BlockedBy,
		&i.RatingsCount,
	)
	return i, err
}

const isUserAdmin = `-- name: IsUserAdmin :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE id = $1
      AND is_admin
)
`

// Роль читается из БД при каждом обращении к /admin. Поэтому выданное или отозванное
// право начинает действовать сразу, а пользователю не нужно получать новый JWT.
// EXISTS всегда возвращает одну строку: удалённый пользователь считается не админом.
func (q *Queries) IsUserAdmin(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserAdmin, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
    nickname    = COALESCE($1, nickname),
    photo_url   = COALESCE($2, photo_url),
    description = COALESCE($3, description)
WHERE id = $4
RETURNING id, nickname, password_hash, photo_url, description, deals_completed, deals_broken, rating, created_at, updated_at, is_admin, is_blocked, blocked_at, blocked_by, ratings_count
`

type UpdateUserProfileParams struct {
	Nickname    pgtype.Text
	PhotoUrl    pgtype.Text
	Description pgtype.Text
	ID          pgtype.UUID
}

// TODO: NULL в аргументе означает «не менять поле», поэтому сбросить photo_url обратно
// в NULL этим запросом нельзя. Понадобится отдельный ClearUserPhoto.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Nickname,
		arg.PhotoUrl,
		arg.Description,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.PasswordHash,
		&i.PhotoUrl,
		&i.Description,
		&i.DealsCompleted,
		&i.DealsBroken,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.BlockedBy,
		&i.RatingsCount,
	)
	return i, err
}
